export const GAMES = [
  // ─── Existentes ───────────────────────────────────────────────────────────
  {
    id: 'tictactoe',
    name: 'Tres en Raya',
    emoji: '❌⭕',
    category: 'strategy',
    description: 'Clásico X y O. ¡Gana 3 rondas!',
    color: 'from-violet-500 to-purple-600',
    players: '2 jugadores',
  },
  {
    id: 'connect4',
    name: 'Cuatro en Raya',
    emoji: '🔴🟡',
    category: 'strategy',
    description: 'Conecta 4 fichas para ganar',
    color: 'from-red-500 to-orange-500',
    players: '2 jugadores',
  },
  {
    id: 'truthordare',
    name: 'Verdad o Reto',
    emoji: '🎯🔥',
    category: 'party',
    description: 'Responde o acepta el reto',
    color: 'from-blue-500 to-cyan-500',
    players: '2 jugadores',
  },
  {
    id: 'wordguess',
    name: 'Adivina la Palabra',
    emoji: '🔤✨',
    category: 'words',
    description: 'Wordle para 2 jugadores',
    color: 'from-green-500 to-emerald-500',
    players: '2 jugadores',
  },
  {
    id: 'rps',
    name: 'Piedra Papel Tijera',
    emoji: '✊✋✌️',
    category: 'reflexes',
    description: 'Modo épico al mejor de 5, 7 u 11',
    color: 'from-amber-500 to-yellow-500',
    players: '2 jugadores',
  },
  {
    id: 'trivia',
    name: 'Trivia',
    emoji: '🧠💡',
    category: 'words',
    description: 'Preguntas y respuestas por turnos',
    color: 'from-pink-500 to-rose-500',
    players: '2 jugadores',
  },
  {
    id: 'taprace',
    name: 'Puntería',
    emoji: '👆⚡',
    category: 'reflexes',
    description: 'Toca objetos lo más rápido posible',
    color: 'from-teal-500 to-green-500',
    players: '2 jugadores',
  },
  {
    id: 'guessnumber',
    name: 'Adivina el Número',
    emoji: '🔢🎯',
    category: 'strategy',
    description: 'Uno piensa, otro adivina',
    color: 'from-indigo-500 to-blue-600',
    players: '2 jugadores',
  },
  {
    id: 'memory',
    name: 'Memoria',
    emoji: '🃏🧠',
    category: 'reflexes',
    description: 'Encuentra las parejas ocultas',
    color: 'from-fuchsia-500 to-purple-500',
    players: '2 jugadores',
  },
  {
    id: 'mathrace',
    name: 'Carrera Matemática',
    emoji: '🔢🏃',
    category: 'reflexes',
    description: 'Resuelve operaciones más rápido',
    color: 'from-cyan-500 to-blue-500',
    players: '2 jugadores',
  },
  {
    id: 'wouldyourather',
    name: '¿Qué Preferirías?',
    emoji: '🤔💭',
    category: 'party',
    description: 'Elige entre dos opciones difíciles',
    color: 'from-purple-500 to-pink-500',
    players: '2 jugadores',
  },
  {
    id: 'drawandguess',
    name: 'Dibuja y Adivina',
    emoji: '🎨🖊️',
    category: 'party',
    description: 'Dibuja y que el otro adivine',
    color: 'from-yellow-500 to-orange-500',
    players: '2 jugadores',
  },
  {
    id: 'reactiongame',
    name: 'Test de Reacción',
    emoji: '⚡🎯',
    category: 'reflexes',
    description: '¿Quién tiene los reflejos más rápidos?',
    color: 'from-green-500 to-teal-500',
    players: '2 jugadores',
  },

  // ─── Nuevos ───────────────────────────────────────────────────────────────
  {
    id: 'battleship',
    name: 'Hundir la Flota',
    emoji: '⚓🚢',
    category: 'strategy',
    description: 'Hunde todos los barcos del rival',
    color: 'from-blue-600 to-indigo-600',
    players: '2 jugadores',
  },
  {
    id: 'hangmanduo',
    name: 'Ahorcado Dúo',
    emoji: '🪢💀',
    category: 'words',
    description: 'Adivina la palabra antes de morir',
    color: 'from-slate-500 to-gray-600',
    players: '2 jugadores',
  },
  {
    id: 'speedtyping',
    name: 'Mecanografía Veloz',
    emoji: '⌨️🏆',
    category: 'reflexes',
    description: '¿Quién escribe más rápido?',
    color: 'from-cyan-600 to-blue-600',
    players: '2 jugadores',
  },
  {
    id: 'colormatch',
    name: 'Stroop Color',
    emoji: '🎨🧠',
    category: 'reflexes',
    description: 'Identifica el color de la tinta. ¡Confusión total!',
    color: 'from-pink-500 to-red-500',
    players: '2 jugadores',
  },
  {
    id: 'quickdraw',
    name: 'Duelo de Reflejos',
    emoji: '⚔️⚡',
    category: 'reflexes',
    description: '¡Toca primero cuando salga la señal!',
    color: 'from-orange-500 to-red-500',
    players: '2 jugadores',
  },
  {
    id: 'emojistory',
    name: 'Historia Emoji',
    emoji: '😂📖',
    category: 'party',
    description: 'Adivina la historia que cuentan los emojis',
    color: 'from-fuchsia-500 to-pink-500',
    players: '2 jugadores',
  },
  {
    id: 'neverhaviever',
    name: 'Yo Nunca…',
    emoji: '🙈🍹',
    category: 'party',
    description: 'El clásico juego de confesiones',
    color: 'from-indigo-500 to-violet-500',
    players: '2 jugadores',
  },
  {
    id: 'wordchain',
    name: 'Cadena de Palabras',
    emoji: '🔤🔗',
    category: 'words',
    description: 'Cada palabra empieza por la última letra',
    color: 'from-teal-500 to-cyan-500',
    players: '2 jugadores',
  },
  {
    id: 'mimicgame',
    name: 'Mímica',
    emoji: '🎭🤫',
    category: 'party',
    description: 'Actúa sin hablar, haz que adivinen',
    color: 'from-amber-500 to-orange-500',
    players: '2 jugadores',
  },
  {
    id: 'numbermemory',
    name: 'Memoria Numérica',
    emoji: '🔢💭',
    category: 'reflexes',
    description: 'Memoriza y repite números cada vez más largos',
    color: 'from-violet-500 to-blue-500',
    players: '2 jugadores',
  },
  {
    id: 'categoryblitz',
    name: 'Ráfaga de Categorías',
    emoji: '⚡📋',
    category: 'words',
    description: 'Di el máximo de palabras de la categoría',
    color: 'from-yellow-500 to-amber-500',
    players: '2 jugadores',
  },
  {
    id: 'twotruthsonelie',
    name: '2 Verdades 1 Mentira',
    emoji: '🤥✅',
    category: 'party',
    description: '¿Puedes detectar la mentira?',
    color: 'from-teal-500 to-green-600',
    players: '2 jugadores',
  },
  {
    id: 'countdown',
    name: 'Letras y Palabras',
    emoji: '🔡🏆',
    category: 'words',
    description: 'Forma la palabra más larga con esas letras',
    color: 'from-emerald-500 to-teal-500',
    players: '2 jugadores',
  },
  {
    id: 'faceoff',
    name: 'Cara a Cara',
    emoji: '⚡🔔',
    category: 'reflexes',
    description: 'Pulsa primero y responde la pregunta',
    color: 'from-red-500 to-pink-500',
    players: '2 jugadores',
  },
  {
    id: 'fingerchop',
    name: 'No Levantes el Dedo',
    emoji: '☝️🪓',
    category: 'reflexes',
    description: '¡Aguanta sin levantar el dedo!',
    color: 'from-slate-600 to-gray-700',
    players: '2 jugadores',
  },
  {
    id: 'riddles',
    name: 'Acertijos',
    emoji: '🤔💡',
    category: 'words',
    description: 'Resuelve acertijos clásicos por turnos',
    color: 'from-amber-400 to-yellow-500',
    players: '2 jugadores',
  },
  {
    id: 'soundboard',
    name: 'Repite el Patrón',
    emoji: '🎵🧠',
    category: 'reflexes',
    description: 'Memoriza y repite la secuencia de colores',
    color: 'from-pink-500 to-fuchsia-500',
    players: '2 jugadores',
  },
  {
    id: 'speedsort',
    name: 'Ordena Rápido',
    emoji: '⚡📦',
    category: 'reflexes',
    description: 'Clasifica el máximo de elementos en 40s',
    color: 'from-green-500 to-lime-500',
    players: '2 jugadores',
  },
  {
    id: 'musicquiz',
    name: 'Quiz Musical',
    emoji: '🎵🏆',
    category: 'words',
    description: 'Preguntas de música por turnos',
    color: 'from-pink-600 to-purple-600',
    players: '2 jugadores',
  },
  {
    id: 'lastlettercity',
    name: 'Ciudades del Mundo',
    emoji: '🌍🏙️',
    category: 'words',
    description: 'Ciudades en cadena — última letra = primera',
    color: 'from-blue-500 to-teal-500',
    players: '2 jugadores',
  },
  {
    id: 'debate',
    name: 'Debate',
    emoji: '🗣️⚖️',
    category: 'party',
    description: 'Defiende tu postura y convence al jurado',
    color: 'from-indigo-500 to-blue-600',
    players: '2 jugadores',
  },
];

export const CATEGORIES = [
  { id: 'all', name: 'Todos', emoji: '🎮' },
  { id: 'strategy', name: 'Estrategia', emoji: '♟️' },
  { id: 'words', name: 'Palabras', emoji: '📝' },
  { id: 'reflexes', name: 'Reflejos', emoji: '⚡' },
  { id: 'party', name: 'Party', emoji: '🎉' },
];