export const GAMES = [
  {
    id: 'tictactoe',
    name: 'Tres en Raya',
    emoji: '❌⭕',
    category: 'strategy',
    description: 'Clásico X y O. ¡Gana 3 rondas!',
    color: 'from-violet-500 to-purple-600',
    players: '2 jugadores',
  },
  {
    id: 'connect4',
    name: 'Cuatro en Raya',
    emoji: '🔴🟡',
    category: 'strategy',
    description: 'Conecta 4 fichas para ganar',
    color: 'from-red-500 to-orange-500',
    players: '2 jugadores',
  },
  {
    id: 'battleship',
    name: 'Hundir la Flota',
    emoji: '🚢💥',
    category: 'strategy',
    description: 'Encuentra y hunde los barcos enemigos',
    color: 'from-blue-500 to-cyan-500',
    players: '2 jugadores',
  },
  {
    id: 'wordguess',
    name: 'Adivina la Palabra',
    emoji: '🔤✨',
    category: 'words',
    description: 'Wordle para 2 jugadores',
    color: 'from-green-500 to-emerald-500',
    players: '2 jugadores',
  },
  {
    id: 'rps',
    name: 'Piedra Papel Tijera',
    emoji: '✊✋✌️',
    category: 'reflexes',
    description: 'Modo épico al mejor de 5, 7 u 11',
    color: 'from-amber-500 to-yellow-500',
    players: '2 jugadores',
  },
  {
    id: 'trivia',
    name: 'Trivia',
    emoji: '🧠💡',
    category: 'words',
    description: 'Preguntas y respuestas por turnos',
    color: 'from-pink-500 to-rose-500',
    players: '2 jugadores',
  },
  {
    id: 'taprace',
    name: 'Puntería',
    emoji: '👆⚡',
    category: 'reflexes',
    description: 'Toca objetos lo más rápido posible',
    color: 'from-teal-500 to-green-500',
    players: '2 jugadores',
  },
  {
    id: 'dice',
    name: 'Dados',
    emoji: '🎲🎯',
    category: 'luck',
    description: 'Yahtzee simplificado para 2',
    color: 'from-indigo-500 to-blue-600',
    players: '2 jugadores',
  },
  {
    id: 'memory',
    name: 'Memoria',
    emoji: '🃏🧠',
    category: 'reflexes',
    description: 'Encuentra las parejas ocultas',
    color: 'from-fuchsia-500 to-purple-500',
    players: '2 jugadores',
  },
  {
    id: 'mathrace',
    name: 'Carrera Matemática',
    emoji: '🔢🏃',
    category: 'reflexes',
    description: 'Resuelve operaciones más rápido',
    color: 'from-cyan-500 to-blue-500',
    players: '2 jugadores',
  },
];

export const CATEGORIES = [
  { id: 'all', name: 'Todos', emoji: '🎮' },
  { id: 'strategy', name: 'Estrategia', emoji: '♟️' },
  { id: 'words', name: 'Palabras', emoji: '📝' },
  { id: 'reflexes', name: 'Reflejos', emoji: '⚡' },
  { id: 'luck', name: 'Suerte', emoji: '🍀' },
];