export const TRIVIA_QUESTIONS = {
  ciencia: [
    { q: "¿Cuál es el planeta más grande del sistema solar?", a: "Júpiter", opts: ["Saturno", "Júpiter", "Neptuno", "Urano"] },
    { q: "¿Qué gas respiramos principalmente?", a: "Oxígeno", opts: ["Nitrógeno", "Oxígeno", "CO2", "Helio"] },
    { q: "¿Cuántos huesos tiene el cuerpo humano adulto?", a: "206", opts: ["206", "300", "180", "256"] },
    { q: "¿Qué vitamina proporciona el sol?", a: "Vitamina D", opts: ["Vitamina A", "Vitamina C", "Vitamina D", "Vitamina B"] },
    { q: "¿Cuál es el metal más ligero?", a: "Litio", opts: ["Aluminio", "Litio", "Sodio", "Magnesio"] },
    { q: "¿Qué planeta es conocido como el planeta rojo?", a: "Marte", opts: ["Venus", "Marte", "Júpiter", "Mercurio"] },
    { q: "¿Cuál es el animal más rápido del mundo?", a: "Guepardo", opts: ["León", "Guepardo", "Águila", "Caballo"] },
    { q: "¿Qué órgano bombea la sangre?", a: "Corazón", opts: ["Pulmón", "Hígado", "Corazón", "Riñón"] },
    { q: "¿Cuál es el elemento químico del agua?", a: "H2O", opts: ["CO2", "H2O", "O2", "NaCl"] },
    { q: "¿Qué fuerza nos mantiene en la Tierra?", a: "Gravedad", opts: ["Magnetismo", "Gravedad", "Fricción", "Inercia"] },
    { q: "¿Cuántos cromosomas tiene el ser humano?", a: "46", opts: ["23", "46", "48", "44"] },
    { q: "¿Qué animal produce miel?", a: "Abeja", opts: ["Avispa", "Abeja", "Mariposa", "Hormiga"] },
    { q: "¿Cuál es el hueso más largo del cuerpo?", a: "Fémur", opts: ["Tibia", "Fémur", "Húmero", "Radio"] },
    { q: "¿Qué tipo de animal es una ballena?", a: "Mamífero", opts: ["Pez", "Mamífero", "Reptil", "Anfibio"] },
    { q: "¿Cuál es la estrella más cercana a la Tierra?", a: "El Sol", opts: ["Sirio", "El Sol", "Próxima Centauri", "Vega"] },
    { q: "¿Qué gas hace que las bebidas tengan burbujas?", a: "CO2", opts: ["Oxígeno", "CO2", "Nitrógeno", "Hidrógeno"] },
    { q: "¿De qué color es la sangre oxigenada?", a: "Roja", opts: ["Azul", "Roja", "Morada", "Verde"] },
    { q: "¿Cuántas patas tiene una araña?", a: "8", opts: ["6", "8", "10", "4"] },
    { q: "¿Qué material se usa para hacer ventanas?", a: "Vidrio", opts: ["Plástico", "Vidrio", "Cristal", "Mica"] },
    { q: "¿Cuál es el océano más grande?", a: "Pacífico", opts: ["Atlántico", "Pacífico", "Índico", "Ártico"] },
    { q: "¿Qué elemento químico tiene el símbolo Fe?", a: "Hierro", opts: ["Flúor", "Hierro", "Fósforo", "Francio"] },
    { q: "¿Cuántas capas tiene la atmósfera terrestre?", a: "5", opts: ["3", "4", "5", "6"] },
    { q: "¿Qué planeta tiene anillos visibles?", a: "Saturno", opts: ["Júpiter", "Saturno", "Urano", "Neptuno"] },
    { q: "¿Cuál es el río más largo del mundo?", a: "Nilo", opts: ["Amazonas", "Nilo", "Yangtsé", "Misisipi"] },
    { q: "¿Qué instrumento mide la temperatura?", a: "Termómetro", opts: ["Barómetro", "Termómetro", "Higrómetro", "Anemómetro"] },
  ],
  historia: [
    { q: "¿En qué año llegó Colón a América?", a: "1492", opts: ["1492", "1500", "1480", "1512"] },
    { q: "¿Quién pintó la Mona Lisa?", a: "Leonardo da Vinci", opts: ["Miguel Ángel", "Leonardo da Vinci", "Rafael", "Botticelli"] },
    { q: "¿Cuál fue la primera civilización?", a: "Sumeria", opts: ["Egipcia", "Sumeria", "Griega", "Romana"] },
    { q: "¿En qué año cayó el Muro de Berlín?", a: "1989", opts: ["1987", "1989", "1991", "1985"] },
    { q: "¿Quién fue el primer presidente de EE.UU.?", a: "George Washington", opts: ["Thomas Jefferson", "George Washington", "Abraham Lincoln", "John Adams"] },
    { q: "¿Qué imperio construyó el Coliseo de Roma?", a: "Romano", opts: ["Griego", "Romano", "Persa", "Bizantino"] },
    { q: "¿En qué siglo fue la Revolución Francesa?", a: "XVIII", opts: ["XVII", "XVIII", "XIX", "XVI"] },
    { q: "¿Quién escribió Don Quijote?", a: "Cervantes", opts: ["Lope de Vega", "Cervantes", "Quevedo", "Calderón"] },
    { q: "¿Qué país inventó la pólvora?", a: "China", opts: ["India", "China", "Arabia", "Grecia"] },
    { q: "¿En qué año terminó la Segunda Guerra Mundial?", a: "1945", opts: ["1943", "1945", "1944", "1946"] },
    { q: "¿Quién descubrió la penicilina?", a: "Alexander Fleming", opts: ["Louis Pasteur", "Alexander Fleming", "Marie Curie", "Robert Koch"] },
    { q: "¿Qué civilización construyó Machu Picchu?", a: "Inca", opts: ["Maya", "Inca", "Azteca", "Olmeca"] },
    { q: "¿En qué año se hundió el Titanic?", a: "1912", opts: ["1910", "1912", "1914", "1908"] },
    { q: "¿Quién fue Cleopatra?", a: "Reina de Egipto", opts: ["Diosa griega", "Reina de Egipto", "Princesa romana", "Emperatriz persa"] },
    { q: "¿Cuántos años duró la Guerra de los Cien Años?", a: "116", opts: ["100", "116", "99", "120"] },
    { q: "¿Qué monumento está en Giza, Egipto?", a: "Las Pirámides", opts: ["El Partenón", "Las Pirámides", "El Coliseo", "Stonehenge"] },
    { q: "¿Quién fue Napoleón Bonaparte?", a: "Emperador francés", opts: ["Rey inglés", "Emperador francés", "Papa", "Zar ruso"] },
    { q: "¿Qué imperio dominó el Mediterráneo?", a: "Romano", opts: ["Persa", "Romano", "Otomano", "Mongol"] },
    { q: "¿En qué siglo se inventó la imprenta?", a: "XV", opts: ["XIV", "XV", "XVI", "XIII"] },
    { q: "¿Quién dijo 'Pienso, luego existo'?", a: "Descartes", opts: ["Platón", "Descartes", "Aristóteles", "Kant"] },
    { q: "¿Qué tratado puso fin a la Primera Guerra Mundial?", a: "Versalles", opts: ["París", "Versalles", "Viena", "Ginebra"] },
    { q: "¿Qué país fue el primero en llegar a la Luna?", a: "Estados Unidos", opts: ["Rusia", "Estados Unidos", "China", "Japón"] },
    { q: "¿Cuál es la escritura más antigua conocida?", a: "Cuneiforme", opts: ["Jeroglíficos", "Cuneiforme", "Alfabeto griego", "Chino"] },
    { q: "¿En qué continente se originó el ser humano?", a: "África", opts: ["Asia", "África", "Europa", "América"] },
    { q: "¿Quién fue Julio César?", a: "Líder romano", opts: ["Rey griego", "Líder romano", "Faraón", "General cartaginés"] },
  ],
  entretenimiento: [
    { q: "¿Quién creó Mickey Mouse?", a: "Walt Disney", opts: ["Warner Bros", "Walt Disney", "Pixar", "DreamWorks"] },
    { q: "¿De qué país es el anime?", a: "Japón", opts: ["China", "Japón", "Corea", "Tailandia"] },
    { q: "¿Cuántas teclas tiene un piano estándar?", a: "88", opts: ["76", "88", "92", "84"] },
    { q: "¿Qué instrumento toca un violinista?", a: "Violín", opts: ["Viola", "Violín", "Chelo", "Contrabajo"] },
    { q: "¿En qué juego se capturan Pokémon?", a: "Pokémon", opts: ["Digimon", "Pokémon", "Yu-Gi-Oh", "Bakugan"] },
    { q: "¿Cuál es la red social de fotos más famosa?", a: "Instagram", opts: ["Facebook", "Instagram", "Twitter", "TikTok"] },
    { q: "¿Qué superhéroe es Bruce Wayne?", a: "Batman", opts: ["Superman", "Batman", "Spider-Man", "Iron Man"] },
    { q: "¿Quién canta 'Despacito'?", a: "Luis Fonsi", opts: ["Daddy Yankee", "Luis Fonsi", "Bad Bunny", "J Balvin"] },
    { q: "¿Qué videojuego tiene bloques y creepers?", a: "Minecraft", opts: ["Roblox", "Minecraft", "Fortnite", "Terraria"] },
    { q: "¿De qué color es Pikachu?", a: "Amarillo", opts: ["Rojo", "Amarillo", "Azul", "Verde"] },
    { q: "¿Quién interpreta a Jack Sparrow?", a: "Johnny Depp", opts: ["Orlando Bloom", "Johnny Depp", "Brad Pitt", "Tom Cruise"] },
    { q: "¿Cuántas notas musicales hay?", a: "7", opts: ["5", "7", "8", "12"] },
    { q: "¿En qué película hay un muñeco de nieve llamado Olaf?", a: "Frozen", opts: ["Frozen", "Moana", "Enredados", "Coco"] },
    { q: "¿Qué saga tiene sables de luz?", a: "Star Wars", opts: ["Star Trek", "Star Wars", "El Señor de los Anillos", "Harry Potter"] },
    { q: "¿Cuál es la consola de Nintendo más vendida?", a: "Nintendo DS", opts: ["Wii", "Nintendo DS", "Switch", "Game Boy"] },
    { q: "¿Quién es el fontanero más famoso de los videojuegos?", a: "Mario", opts: ["Luigi", "Mario", "Sonic", "Link"] },
    { q: "¿Qué película ganó el primer Óscar?", a: "Alas", opts: ["Amanecer", "Alas", "Metrópolis", "El cantor de jazz"] },
    { q: "¿De qué país son los Beatles?", a: "Inglaterra", opts: ["EEUU", "Inglaterra", "Irlanda", "Australia"] },
    { q: "¿Qué mago va a Hogwarts?", a: "Harry Potter", opts: ["Gandalf", "Harry Potter", "Merlín", "Dumbledore"] },
    { q: "¿Qué plataforma es famosa por sus bailes cortos?", a: "TikTok", opts: ["YouTube", "TikTok", "Instagram", "Snapchat"] },
    { q: "¿Cuántas películas hay de Toy Story?", a: "4", opts: ["3", "4", "5", "6"] },
    { q: "¿Qué animal es Simba?", a: "León", opts: ["Tigre", "León", "Leopardo", "Pantera"] },
    { q: "¿Quién es el creador de Facebook?", a: "Mark Zuckerberg", opts: ["Elon Musk", "Mark Zuckerberg", "Jeff Bezos", "Bill Gates"] },
    { q: "¿En qué juego se construyen fortalezas y se lucha?", a: "Fortnite", opts: ["PUBG", "Fortnite", "Apex", "Warzone"] },
    { q: "¿Qué banda cantó 'Bohemian Rhapsody'?", a: "Queen", opts: ["Beatles", "Queen", "Rolling Stones", "Pink Floyd"] },
  ],
  deporte: [
    { q: "¿Cuántos jugadores hay en un equipo de fútbol?", a: "11", opts: ["9", "11", "10", "12"] },
    { q: "¿En qué deporte se usa una raqueta y pelota amarilla?", a: "Tenis", opts: ["Bádminton", "Tenis", "Squash", "Pádel"] },
    { q: "¿Cuánto dura un partido de fútbol?", a: "90 minutos", opts: ["60 minutos", "90 minutos", "120 minutos", "80 minutos"] },
    { q: "¿En qué país se inventó el baloncesto?", a: "EE.UU.", opts: ["Canadá", "EE.UU.", "Inglaterra", "España"] },
    { q: "¿Cuántos sets hay en un partido de tenis?", a: "3 o 5", opts: ["2 o 4", "3 o 5", "4 o 6", "5 o 7"] },
    { q: "¿Qué selección ha ganado más mundiales de fútbol?", a: "Brasil", opts: ["Alemania", "Brasil", "Argentina", "Italia"] },
    { q: "¿En qué deporte se hace un 'home run'?", a: "Béisbol", opts: ["Cricket", "Béisbol", "Softball", "Golf"] },
    { q: "¿Cuánto mide una cancha de baloncesto de largo?", a: "28 metros", opts: ["25 metros", "28 metros", "30 metros", "32 metros"] },
    { q: "¿Qué deporte practica Usain Bolt?", a: "Atletismo", opts: ["Natación", "Atletismo", "Ciclismo", "Fútbol"] },
    { q: "¿Cada cuántos años se celebran los Juegos Olímpicos?", a: "4 años", opts: ["2 años", "4 años", "3 años", "5 años"] },
    { q: "¿Qué deporte se juega en Wimbledon?", a: "Tenis", opts: ["Golf", "Tenis", "Cricket", "Polo"] },
    { q: "¿Cuántos jugadores hay en un equipo de voleibol?", a: "6", opts: ["5", "6", "7", "8"] },
    { q: "¿En qué país se creó el judo?", a: "Japón", opts: ["China", "Japón", "Corea", "Brasil"] },
    { q: "¿Qué deporte usa un disco en vez de pelota?", a: "Hockey hielo", opts: ["Hockey hielo", "Lacrosse", "Polo", "Curling"] },
    { q: "¿Cuántos puntos vale un gol en fútbol?", a: "1", opts: ["1", "2", "3", "6"] },
    { q: "¿Qué nadador tiene más medallas olímpicas?", a: "Michael Phelps", opts: ["Mark Spitz", "Michael Phelps", "Ian Thorpe", "Ryan Lochte"] },
    { q: "¿En qué deporte se usa el término 'ace'?", a: "Tenis", opts: ["Golf", "Tenis", "Voleibol", "Bádminton"] },
    { q: "¿De qué país es el sumo?", a: "Japón", opts: ["China", "Japón", "Mongolia", "Corea"] },
    { q: "¿Cuántos periodos tiene un partido de hockey hielo?", a: "3", opts: ["2", "3", "4", "5"] },
    { q: "¿Qué deporte se practica en el Tour de Francia?", a: "Ciclismo", opts: ["Atletismo", "Ciclismo", "Natación", "Triatlón"] },
    { q: "¿Cuántos jugadores hay en un equipo de rugby?", a: "15", opts: ["11", "13", "15", "7"] },
    { q: "¿En qué año fue el primer Mundial de fútbol?", a: "1930", opts: ["1928", "1930", "1934", "1926"] },
    { q: "¿Qué país albergó los JJOO de 2020?", a: "Japón", opts: ["China", "Japón", "Francia", "Brasil"] },
    { q: "¿Cuántos hoyos tiene un campo de golf?", a: "18", opts: ["9", "18", "12", "24"] },
    { q: "¿Qué deporte practican los Harlem Globetrotters?", a: "Baloncesto", opts: ["Fútbol", "Baloncesto", "Béisbol", "Voleibol"] },
  ],
};