export const TRIVIA_QUESTIONS_HARD = {
  ciencia: [
    { q: "¿Cuál es el número atómico del oro?", a: "79", opts: ["73", "79", "82", "76"] },
    { q: "¿Qué partícula subatómica tiene carga negativa?", a: "Electrón", opts: ["Protón", "Neutrón", "Electrón", "Quark"] },
    { q: "¿Cuál es la constante de Planck (aproximada)?", a: "6.63×10⁻³⁴ J·s", opts: ["3.14×10⁻³⁴ J·s", "6.63×10⁻³⁴ J·s", "9.11×10⁻³¹ J·s", "1.38×10⁻²³ J·s"] },
    { q: "¿Qué proteína transporta el oxígeno en la sangre?", a: "Hemoglobina", opts: ["Albumina", "Hemoglobina", "Mioglobina", "Fibrinógeno"] },
    { q: "¿Cuántos pares de cromosomas tiene el ser humano?", a: "23", opts: ["22", "23", "24", "46"] },
    { q: "¿Qué ley describe la relación entre presión y volumen de un gas?", a: "Ley de Boyle", opts: ["Ley de Charles", "Ley de Boyle", "Ley de Gay-Lussac", "Ley de Dalton"] },
    { q: "¿Cuál es el símbolo del elemento Wolframio?", a: "W", opts: ["Wf", "W", "Wo", "Wl"] },
    { q: "¿Qué tipo de enlace une los nucleótidos en el ADN?", a: "Fosfodiéster", opts: ["Peptídico", "Fosfodiéster", "Glicosídico", "Disulfuro"] },
    { q: "¿Cuál es la velocidad de la luz en el vacío?", a: "299.792.458 m/s", opts: ["299.792.458 m/s", "300.000.000 m/s", "299.000.000 m/s", "3×10⁸ km/s"] },
    { q: "¿Qué organelo produce ATP en la célula?", a: "Mitocondria", opts: ["Ribosoma", "Mitocondria", "Aparato de Golgi", "Lisosoma"] },
    { q: "¿Cuál es el punto de fusión del tungsteno?", a: "3.422 °C", opts: ["1.850 °C", "2.700 °C", "3.422 °C", "4.000 °C"] },
    { q: "¿Qué principio establece que no es posible conocer simultáneamente posición y momento de una partícula?", a: "Heisenberg", opts: ["Schrödinger", "Heisenberg", "Pauli", "Bohr"] },
    { q: "¿Cuántos aminoácidos esenciales existen para el ser humano?", a: "9", opts: ["8", "9", "10", "12"] },
    { q: "¿Qué elemento tiene mayor electronegatividad?", a: "Flúor", opts: ["Oxígeno", "Cloro", "Flúor", "Nitrógeno"] },
    { q: "¿Qué fenómeno explica el corrimiento al rojo de las galaxias?", a: "Efecto Doppler", opts: ["Efecto Doppler", "Lente gravitacional", "Radiación de fondo", "Efecto fotoeléctrico"] },
  ],
  historia: [
    { q: "¿En qué año se firmó la Magna Carta?", a: "1215", opts: ["1095", "1215", "1348", "1189"] },
    { q: "¿Quién fue el último zar de Rusia?", a: "Nicolás II", opts: ["Alejandro III", "Nicolás II", "Alejandro II", "Pablo I"] },
    { q: "¿Qué batalla puso fin al Imperio Napoleónico?", a: "Waterloo", opts: ["Austerlitz", "Waterloo", "Trafalgar", "Leipzig"] },
    { q: "¿En qué año se firmó el Tratado de Westfalia?", a: "1648", opts: ["1618", "1648", "1672", "1700"] },
    { q: "¿Quién fue el fundador del Imperio mongol?", a: "Gengis Kan", opts: ["Tamerlán", "Kublai Kan", "Gengis Kan", "Ogodei"] },
    { q: "¿Qué civilización inventó el sistema decimal posicional?", a: "Babilónica", opts: ["India", "Babilónica", "Árabe", "China"] },
    { q: "¿En qué año Bizancio cayó ante el Imperio Otomano?", a: "1453", opts: ["1389", "1453", "1492", "1517"] },
    { q: "¿Cómo se llamaba el tratado de paz de la Primera Guerra Mundial?", a: "Tratado de Versalles", opts: ["Tratado de París", "Tratado de Versalles", "Tratado de Utrecht", "Tratado de Viena"] },
    { q: "¿Qué filósofo griego fue maestro de Alejandro Magno?", a: "Aristóteles", opts: ["Platón", "Sócrates", "Aristóteles", "Epicuro"] },
    { q: "¿En qué año fue la Revolución Rusa de octubre?", a: "1917", opts: ["1905", "1917", "1918", "1920"] },
    { q: "¿Qué cultura construyó Teotihuacán?", a: "Desconocida", opts: ["Azteca", "Maya", "Desconocida", "Olmeca"] },
    { q: "¿Quién escribió 'El Príncipe'?", a: "Maquiavelo", opts: ["Hobbes", "Maquiavelo", "Rousseau", "Locke"] },
    { q: "¿Cuánto duró el Imperio romano de Occidente?", a: "~500 años", opts: ["~300 años", "~400 años", "~500 años", "~700 años"] },
    { q: "¿En qué ciudad se firmó la Declaración de Independencia de EE.UU.?", a: "Filadelfia", opts: ["Boston", "Filadelfia", "Nueva York", "Washington"] },
    { q: "¿Quién fue el primer secretario general de la ONU?", a: "Trygve Lie", opts: ["Dag Hammarskjöld", "Trygve Lie", "U Thant", "Kurt Waldheim"] },
  ],
  entretenimiento: [
    { q: "¿Cuántos fotogramas por segundo tiene el cine estándar?", a: "24", opts: ["18", "24", "30", "60"] },
    { q: "¿Qué director filmó '2001: Una odisea del espacio'?", a: "Stanley Kubrick", opts: ["Steven Spielberg", "Stanley Kubrick", "Ridley Scott", "George Lucas"] },
    { q: "¿En qué año se estrenó el primer videojuego comercial 'Pong'?", a: "1972", opts: ["1969", "1972", "1975", "1977"] },
    { q: "¿Qué compositor escribió la 'Quinta Sinfonía'?", a: "Beethoven", opts: ["Mozart", "Beethoven", "Bach", "Brahms"] },
    { q: "¿Quién escribió 'Cien años de soledad'?", a: "Gabriel García Márquez", opts: ["Mario Vargas Llosa", "Gabriel García Márquez", "Julio Cortázar", "Pablo Neruda"] },
    { q: "¿Cuántos libros tiene la serie original de Harry Potter?", a: "7", opts: ["6", "7", "8", "9"] },
    { q: "¿En qué año se fundó la empresa Nintendo?", a: "1889", opts: ["1950", "1974", "1889", "1932"] },
    { q: "¿Qué película ganó el Óscar a mejor película en 1994?", a: "Forrest Gump", opts: ["Pulp Fiction", "Forrest Gump", "El rey león", "Shawshank"] },
    { q: "¿Quién compuso la ópera 'La Traviata'?", a: "Verdi", opts: ["Puccini", "Verdi", "Wagner", "Mozart"] },
    { q: "¿Qué artista pintó 'La persistencia de la memoria'?", a: "Dalí", opts: ["Picasso", "Dalí", "Miró", "Kandinsky"] },
    { q: "¿Qué lenguaje de programación usa el motor del juego DOOM original?", a: "C", opts: ["C++", "C", "Assembly", "Fortran"] },
    { q: "¿En qué país se originó el género musical K-pop?", a: "Corea del Sur", opts: ["Japón", "China", "Corea del Sur", "Corea del Norte"] },
    { q: "¿Cuántas temporadas tiene la serie 'Breaking Bad'?", a: "5", opts: ["4", "5", "6", "7"] },
    { q: "¿Qué actor interpretó a Hannibal Lecter en 'El silencio de los corderos'?", a: "Anthony Hopkins", opts: ["Jack Nicholson", "Anthony Hopkins", "Gary Oldman", "Robert De Niro"] },
    { q: "¿Cuál es la novela más larga jamás escrita según el Libro Guinness?", a: "En busca del tiempo perdido", opts: ["Guerra y paz", "En busca del tiempo perdido", "Los miserables", "El Quijote"] },
  ],
  deporte: [
    { q: "¿Cuántos metros mide un maratón?", a: "42.195", opts: ["42.000", "42.195", "42.500", "43.000"] },
    { q: "¿En qué año se celebraron los primeros Juegos Olímpicos modernos?", a: "1896", opts: ["1888", "1896", "1900", "1904"] },
    { q: "¿Cuántos Grand Slams de tenis existen?", a: "4", opts: ["3", "4", "5", "6"] },
    { q: "¿Qué tenista tiene más títulos de Grand Slam masculinos históricos?", a: "Novak Djokovic", opts: ["Roger Federer", "Rafael Nadal", "Novak Djokovic", "Pete Sampras"] },
    { q: "¿Cuántos rounds tiene un combate de boxeo profesional estándar?", a: "12", opts: ["10", "12", "15", "8"] },
    { q: "¿Qué peso tiene un disco de hockey hielo oficial?", a: "170 g", opts: ["140 g", "155 g", "170 g", "200 g"] },
    { q: "¿En qué deporte se usa el término 'épée'?", a: "Esgrima", opts: ["Polo", "Esgrima", "Equitación", "Jabalina"] },
    { q: "¿Cuál es la longitud oficial de una piscina olímpica?", a: "50 metros", opts: ["25 metros", "50 metros", "100 metros", "75 metros"] },
    { q: "¿Qué club ha ganado más Champions League?", a: "Real Madrid", opts: ["Barcelona", "Real Madrid", "Bayern Múnich", "AC Milan"] },
    { q: "¿Cuántos jugadores hay en un equipo de water polo?", a: "7", opts: ["6", "7", "8", "9"] },
    { q: "¿Quién tiene el récord mundial de los 100m lisos?", a: "Usain Bolt", opts: ["Justin Gatlin", "Usain Bolt", "Tyson Gay", "Asafa Powell"] },
    { q: "¿En qué país se inventó el rugby?", a: "Inglaterra", opts: ["Irlanda", "Escocia", "Inglaterra", "Gales"] },
    { q: "¿Cuál es el ancho de la portería de fútbol en metros?", a: "7.32", opts: ["7.00", "7.32", "7.50", "8.00"] },
    { q: "¿Qué material recubre una pelota de tenis?", a: "Fieltro", opts: ["Goma", "Fieltro", "Nylon", "Cuero"] },
    { q: "¿Cuántos atletas corren el relevo 4×100 por equipo?", a: "4", opts: ["3", "4", "5", "6"] },
    { q: "¿Qué deporte practica el campeón Eliud Kipchoge?", a: "Maratón", opts: ["Triatlón", "Maratón", "Ciclismo", "Decatlón"] },
    { q: "¿En qué deporte existe la posición 'libero'?", a: "Voleibol", opts: ["Balonmano", "Voleibol", "Rugby", "Waterpolo"] },
    { q: "¿Cuántos metros tiene una piscina olímpica estándar?", a: "50", opts: ["25", "50", "75", "100"] },
    { q: "¿Qué país tiene más medallas olímpicas en la historia?", a: "Estados Unidos", opts: ["Rusia", "China", "Estados Unidos", "Alemania"] },
    { q: "¿En qué año se retiro Roger Federer del tenis profesional?", a: "2022", opts: ["2020", "2021", "2022", "2023"] },
    { q: "¿Qué deporte tiene las reglas del 'offside'?", a: "Fútbol", opts: ["Rugby", "Fútbol", "Hockey", "Baloncesto"] },
    { q: "¿Cuántos jugadores en campo tiene el fútbol americano?", a: "11", opts: ["9", "10", "11", "12"] },
    { q: "¿Quién tiene más Balones de Oro históricos hasta 2024?", a: "Lionel Messi", opts: ["Cristiano Ronaldo", "Lionel Messi", "Ronaldo Nazário", "Zidane"] },
    { q: "¿Qué deporte se juega en el Masters de Augusta?", a: "Golf", opts: ["Tenis", "Golf", "Polo", "Cricket"] },
    { q: "¿Cuánto pesa un balón oficial de fútbol sala?", a: "400-440g", opts: ["300-350g", "400-440g", "500-540g", "600-650g"] },
    { q: "¿En qué deporte existe la 'vuelta americana'?", a: "Ciclismo", opts: ["Atletismo", "Natación", "Ciclismo", "Patinaje"] },
    { q: "¿Qué país inventó el críquet?", a: "Inglaterra", opts: ["India", "Australia", "Inglaterra", "Sudáfrica"] },
  ],
};

// Additional questions pool to extend variety
export const TRIVIA_QUESTIONS_EXTRA = {
  ciencia: [
    { q: "¿Qué planeta tiene la mayor cantidad de lunas?", a: "Saturno", opts: ["Júpiter", "Saturno", "Urano", "Neptuno"] },
    { q: "¿Cuánto tarda la luz del Sol en llegar a la Tierra?", a: "8 minutos", opts: ["1 minuto", "8 minutos", "20 minutos", "1 hora"] },
    { q: "¿Qué es la fotosíntesis?", a: "Proceso de las plantas para producir energía", opts: ["Proceso de respiración animal", "Proceso de las plantas para producir energía", "División celular", "Digestión de minerales"] },
    { q: "¿Cuántos lados tiene un hexágono?", a: "6", opts: ["5", "6", "7", "8"] },
    { q: "¿Qué tipo de energía produce el Sol?", a: "Nuclear", opts: ["Química", "Nuclear", "Eléctrica", "Mecánica"] },
    { q: "¿Cuál es el gas más abundante en la atmósfera terrestre?", a: "Nitrógeno", opts: ["Oxígeno", "Nitrógeno", "CO2", "Argón"] },
    { q: "¿Qué órgano filtra la sangre en el cuerpo humano?", a: "Riñón", opts: ["Hígado", "Riñón", "Páncreas", "Bazo"] },
    { q: "¿Cuántas alas tiene una mosca?", a: "2", opts: ["2", "4", "6", "1"] },
    { q: "¿Qué es un agujero negro?", a: "Región del espacio con gravedad extrema", opts: ["Un planeta muerto", "Una estrella fría", "Región del espacio con gravedad extrema", "Un vacío sin materia"] },
    { q: "¿Cuántos dientes tiene un adulto con juicio?", a: "32", opts: ["28", "30", "32", "34"] },
    { q: "¿Qué vitamina es esencial para la coagulación de la sangre?", a: "Vitamina K", opts: ["Vitamina A", "Vitamina C", "Vitamina K", "Vitamina E"] },
    { q: "¿Cuál es la capa de la Tierra más caliente?", a: "Núcleo", opts: ["Corteza", "Manto", "Núcleo", "Litosfera"] },
    { q: "¿Qué animal tiene la lengua más larga en proporción?", a: "Camaleón", opts: ["Serpiente", "Jirafa", "Camaleón", "Oso hormiguero"] },
    { q: "¿Cuántas neuronas tiene el cerebro humano aproximadamente?", a: "86.000 millones", opts: ["1.000 millones", "10.000 millones", "86.000 millones", "500.000 millones"] },
    { q: "¿Qué es la mitosis?", a: "División celular", opts: ["Fusión celular", "División celular", "Muerte celular", "Respiración celular"] },
  ],
  historia: [
    { q: "¿En qué año comenzó la Primera Guerra Mundial?", a: "1914", opts: ["1910", "1914", "1916", "1912"] },
    { q: "¿Quién fue el líder de la Revolución Cubana?", a: "Fidel Castro", opts: ["Ernesto Guevara", "Fidel Castro", "Raúl Castro", "Camilo Cienfuegos"] },
    { q: "¿Qué civilización construyó el Partenón?", a: "Griega", opts: ["Romana", "Griega", "Egipcia", "Persa"] },
    { q: "¿En qué año se independizó la India del Reino Unido?", a: "1947", opts: ["1945", "1947", "1950", "1952"] },
    { q: "¿Quién inventó el teléfono?", a: "Alexander Graham Bell", opts: ["Thomas Edison", "Alexander Graham Bell", "Nikola Tesla", "Guglielmo Marconi"] },
    { q: "¿En qué año se fundó la ONU?", a: "1945", opts: ["1919", "1939", "1945", "1950"] },
    { q: "¿Quién fue el primer hombre en el espacio?", a: "Yuri Gagarin", opts: ["Neil Armstrong", "Yuri Gagarin", "Alan Shepard", "Buzz Aldrin"] },
    { q: "¿En qué año fue el descubrimiento de América?", a: "1492", opts: ["1492", "1488", "1500", "1502"] },
    { q: "¿Qué país fue el primero en dar voto a la mujer?", a: "Nueva Zelanda", opts: ["Suecia", "Reino Unido", "Nueva Zelanda", "Estados Unidos"] },
    { q: "¿Cuánto duró la Segunda Guerra Mundial?", a: "6 años", opts: ["4 años", "5 años", "6 años", "7 años"] },
    { q: "¿Quién fue el primer faraón de Egipto?", a: "Menes", opts: ["Ramsés II", "Tutankamón", "Menes", "Cleopatra"] },
    { q: "¿En qué año cayó el Imperio Romano de Occidente?", a: "476 d.C.", opts: ["410 d.C.", "455 d.C.", "476 d.C.", "500 d.C."] },
    { q: "¿Qué invento es de Thomas Edison?", a: "Bombilla eléctrica", opts: ["Teléfono", "Radio", "Bombilla eléctrica", "Automóvil"] },
    { q: "¿En qué país nació Simón Bolívar?", a: "Venezuela", opts: ["Colombia", "Venezuela", "Perú", "Ecuador"] },
    { q: "¿Quién escribió 'El Capital'?", a: "Karl Marx", opts: ["Friedrich Engels", "Karl Marx", "Lenin", "Trotsky"] },
  ],
  entretenimiento: [
    { q: "¿Cuántos personajes principales hay en 'Friends'?", a: "6", opts: ["4", "5", "6", "7"] },
    { q: "¿Quién es el protagonista de 'Breaking Bad'?", a: "Walter White", opts: ["Jesse Pinkman", "Walter White", "Saul Goodman", "Hank Schrader"] },
    { q: "¿En qué año salió el iPhone original?", a: "2007", opts: ["2005", "2006", "2007", "2008"] },
    { q: "¿Qué película de Pixar fue la primera?", a: "Toy Story", opts: ["A Bug's Life", "Toy Story", "Monsters Inc", "Finding Nemo"] },
    { q: "¿Quién es el cantante de Bohemian Rhapsody?", a: "Freddie Mercury", opts: ["David Bowie", "Freddie Mercury", "Mick Jagger", "Robert Plant"] },
    { q: "¿Cuántos capítulos tiene 'Game of Thrones'?", a: "73", opts: ["63", "68", "73", "80"] },
    { q: "¿Qué actor hace de Iron Man?", a: "Robert Downey Jr.", opts: ["Chris Evans", "Robert Downey Jr.", "Chris Hemsworth", "Mark Ruffalo"] },
    { q: "¿Cuántos libros tiene la saga 'El Señor de los Anillos'?", a: "3", opts: ["2", "3", "4", "6"] },
    { q: "¿Cuál es la plataforma de streaming con más suscriptores?", a: "Netflix", opts: ["Disney+", "Netflix", "Amazon Prime", "HBO Max"] },
    { q: "¿Qué artista tiene más streams en Spotify históricamente?", a: "The Weeknd", opts: ["Drake", "Ed Sheeran", "The Weeknd", "Bad Bunny"] },
    { q: "¿En qué año se lanzó YouTube?", a: "2005", opts: ["2003", "2004", "2005", "2006"] },
    { q: "¿Qué personaje dijo 'Que la fuerza te acompañe'?", a: "Obi-Wan Kenobi", opts: ["Luke Skywalker", "Obi-Wan Kenobi", "Yoda", "Qui-Gon Jinn"] },
    { q: "¿Cuántas temporadas tiene 'Stranger Things'?", a: "5", opts: ["3", "4", "5", "6"] },
    { q: "¿Quién canta 'Shape of You'?", a: "Ed Sheeran", opts: ["Justin Bieber", "Ed Sheeran", "Bruno Mars", "Charlie Puth"] },
    { q: "¿En qué ciudad está ambientada 'Narcos'?", a: "Medellín", opts: ["Bogotá", "Medellín", "Cali", "Cartagena"] },
  ],
  deporte: [
    { q: "¿Cuántos puntos vale un triple en baloncesto?", a: "3", opts: ["2", "3", "4", "5"] },
    { q: "¿En qué deporte se usa el término 'smash'?", a: "Bádminton", opts: ["Tenis", "Bádminton", "Squash", "Pádel"] },
    { q: "¿Qué equipo tiene más títulos de la NBA?", a: "Boston Celtics", opts: ["Los Angeles Lakers", "Boston Celtics", "Chicago Bulls", "Golden State Warriors"] },
    { q: "¿Cuántas tarjetas amarillas dan una expulsión en fútbol?", a: "2", opts: ["1", "2", "3", "4"] },
    { q: "¿En qué país se inventó el béisbol?", a: "EE.UU.", opts: ["Cuba", "EE.UU.", "Canadá", "República Dominicana"] },
    { q: "¿Cuántos kilómetros tiene una etapa larga del Tour de Francia?", a: "~200 km", opts: ["~100 km", "~150 km", "~200 km", "~300 km"] },
    { q: "¿Qué deporte practica LeBron James?", a: "Baloncesto", opts: ["Fútbol", "Baloncesto", "Béisbol", "Fútbol americano"] },
    { q: "¿Cuántos jugadores tiene un equipo de polo?", a: "4", opts: ["3", "4", "5", "6"] },
    { q: "¿Qué país ha ganado más veces la Copa Davis?", a: "Estados Unidos", opts: ["España", "Australia", "Estados Unidos", "Francia"] },
    { q: "¿En qué deporte está el 'bunker'?", a: "Golf", opts: ["Béisbol", "Cricket", "Golf", "Rugby"] },
    { q: "¿Cuántos metros es el salto de longitud del récord mundial?", a: "8.95 m", opts: ["8.50 m", "8.75 m", "8.95 m", "9.10 m"] },
    { q: "¿Qué club español ha ganado más Ligas?", a: "Real Madrid", opts: ["Barcelona", "Real Madrid", "Atlético de Madrid", "Valencia"] },
    { q: "¿Cuántos jugadores tiene un equipo de béisbol en el campo?", a: "9", opts: ["8", "9", "10", "11"] },
    { q: "¿En qué deporte existe el 'try'?", a: "Rugby", opts: ["Fútbol americano", "Rugby", "Cricket", "Polo"] },
    { q: "¿Cuántas disciplinas tiene el triatlón?", a: "3", opts: ["2", "3", "4", "5"] },
  ],
};

export const TRIVIA_QUESTIONS = {
  ciencia: [
    { q: "¿Cuál es el planeta más grande del sistema solar?", a: "Júpiter", opts: ["Saturno", "Júpiter", "Neptuno", "Urano"] },
    { q: "¿Qué gas respiramos principalmente?", a: "Oxígeno", opts: ["Nitrógeno", "Oxígeno", "CO2", "Helio"] },
    { q: "¿Cuántos huesos tiene el cuerpo humano adulto?", a: "206", opts: ["206", "300", "180", "256"] },
    { q: "¿Qué vitamina proporciona el sol?", a: "Vitamina D", opts: ["Vitamina A", "Vitamina C", "Vitamina D", "Vitamina B"] },
    { q: "¿Cuál es el metal más ligero?", a: "Litio", opts: ["Aluminio", "Litio", "Sodio", "Magnesio"] },
    { q: "¿Qué planeta es conocido como el planeta rojo?", a: "Marte", opts: ["Venus", "Marte", "Júpiter", "Mercurio"] },
    { q: "¿Cuál es el animal más rápido del mundo?", a: "Guepardo", opts: ["León", "Guepardo", "Águila", "Caballo"] },
    { q: "¿Qué órgano bombea la sangre?", a: "Corazón", opts: ["Pulmón", "Hígado", "Corazón", "Riñón"] },
    { q: "¿Cuál es el elemento químico del agua?", a: "H2O", opts: ["CO2", "H2O", "O2", "NaCl"] },
    { q: "¿Qué fuerza nos mantiene en la Tierra?", a: "Gravedad", opts: ["Magnetismo", "Gravedad", "Fricción", "Inercia"] },
    { q: "¿Cuántos cromosomas tiene el ser humano?", a: "46", opts: ["23", "46", "48", "44"] },
    { q: "¿Qué animal produce miel?", a: "Abeja", opts: ["Avispa", "Abeja", "Mariposa", "Hormiga"] },
    { q: "¿Cuál es el hueso más largo del cuerpo?", a: "Fémur", opts: ["Tibia", "Fémur", "Húmero", "Radio"] },
    { q: "¿Qué tipo de animal es una ballena?", a: "Mamífero", opts: ["Pez", "Mamífero", "Reptil", "Anfibio"] },
    { q: "¿Cuál es la estrella más cercana a la Tierra?", a: "El Sol", opts: ["Sirio", "El Sol", "Próxima Centauri", "Vega"] },
    { q: "¿Qué gas hace que las bebidas tengan burbujas?", a: "CO2", opts: ["Oxígeno", "CO2", "Nitrógeno", "Hidrógeno"] },
    { q: "¿De qué color es la sangre oxigenada?", a: "Roja", opts: ["Azul", "Roja", "Morada", "Verde"] },
    { q: "¿Cuántas patas tiene una araña?", a: "8", opts: ["6", "8", "10", "4"] },
    { q: "¿Qué material se usa para hacer ventanas?", a: "Vidrio", opts: ["Plástico", "Vidrio", "Cristal", "Mica"] },
    { q: "¿Cuál es el océano más grande?", a: "Pacífico", opts: ["Atlántico", "Pacífico", "Índico", "Ártico"] },
    { q: "¿Qué elemento químico tiene el símbolo Fe?", a: "Hierro", opts: ["Flúor", "Hierro", "Fósforo", "Francio"] },
    { q: "¿Cuántas capas tiene la atmósfera terrestre?", a: "5", opts: ["3", "4", "5", "6"] },
    { q: "¿Qué planeta tiene anillos visibles?", a: "Saturno", opts: ["Júpiter", "Saturno", "Urano", "Neptuno"] },
    { q: "¿Cuál es el río más largo del mundo?", a: "Nilo", opts: ["Amazonas", "Nilo", "Yangtsé", "Misisipi"] },
    { q: "¿Qué instrumento mide la temperatura?", a: "Termómetro", opts: ["Barómetro", "Termómetro", "Higrómetro", "Anemómetro"] },
  ],
  historia: [
    { q: "¿En qué año llegó Colón a América?", a: "1492", opts: ["1492", "1500", "1480", "1512"] },
    { q: "¿Quién pintó la Mona Lisa?", a: "Leonardo da Vinci", opts: ["Miguel Ángel", "Leonardo da Vinci", "Rafael", "Botticelli"] },
    { q: "¿Cuál fue la primera civilización?", a: "Sumeria", opts: ["Egipcia", "Sumeria", "Griega", "Romana"] },
    { q: "¿En qué año cayó el Muro de Berlín?", a: "1989", opts: ["1987", "1989", "1991", "1985"] },
    { q: "¿Quién fue el primer presidente de EE.UU.?", a: "George Washington", opts: ["Thomas Jefferson", "George Washington", "Abraham Lincoln", "John Adams"] },
    { q: "¿Qué imperio construyó el Coliseo de Roma?", a: "Romano", opts: ["Griego", "Romano", "Persa", "Bizantino"] },
    { q: "¿En qué siglo fue la Revolución Francesa?", a: "XVIII", opts: ["XVII", "XVIII", "XIX", "XVI"] },
    { q: "¿Quién escribió Don Quijote?", a: "Cervantes", opts: ["Lope de Vega", "Cervantes", "Quevedo", "Calderón"] },
    { q: "¿Qué país inventó la pólvora?", a: "China", opts: ["India", "China", "Arabia", "Grecia"] },
    { q: "¿En qué año terminó la Segunda Guerra Mundial?", a: "1945", opts: ["1943", "1945", "1944", "1946"] },
    { q: "¿Quién descubrió la penicilina?", a: "Alexander Fleming", opts: ["Louis Pasteur", "Alexander Fleming", "Marie Curie", "Robert Koch"] },
    { q: "¿Qué civilización construyó Machu Picchu?", a: "Inca", opts: ["Maya", "Inca", "Azteca", "Olmeca"] },
    { q: "¿En qué año se hundió el Titanic?", a: "1912", opts: ["1910", "1912", "1914", "1908"] },
    { q: "¿Quién fue Cleopatra?", a: "Reina de Egipto", opts: ["Diosa griega", "Reina de Egipto", "Princesa romana", "Emperatriz persa"] },
    { q: "¿Cuántos años duró la Guerra de los Cien Años?", a: "116", opts: ["100", "116", "99", "120"] },
    { q: "¿Qué monumento está en Giza, Egipto?", a: "Las Pirámides", opts: ["El Partenón", "Las Pirámides", "El Coliseo", "Stonehenge"] },
    { q: "¿Quién fue Napoleón Bonaparte?", a: "Emperador francés", opts: ["Rey inglés", "Emperador francés", "Papa", "Zar ruso"] },
    { q: "¿Qué imperio dominó el Mediterráneo?", a: "Romano", opts: ["Persa", "Romano", "Otomano", "Mongol"] },
    { q: "¿En qué siglo se inventó la imprenta?", a: "XV", opts: ["XIV", "XV", "XVI", "XIII"] },
    { q: "¿Quién dijo 'Pienso, luego existo'?", a: "Descartes", opts: ["Platón", "Descartes", "Aristóteles", "Kant"] },
    { q: "¿Qué tratado puso fin a la Primera Guerra Mundial?", a: "Versalles", opts: ["París", "Versalles", "Viena", "Ginebra"] },
    { q: "¿Qué país fue el primero en llegar a la Luna?", a: "Estados Unidos", opts: ["Rusia", "Estados Unidos", "China", "Japón"] },
    { q: "¿Cuál es la escritura más antigua conocida?", a: "Cuneiforme", opts: ["Jeroglíficos", "Cuneiforme", "Alfabeto griego", "Chino"] },
    { q: "¿En qué continente se originó el ser humano?", a: "África", opts: ["Asia", "África", "Europa", "América"] },
    { q: "¿Quién fue Julio César?", a: "Líder romano", opts: ["Rey griego", "Líder romano", "Faraón", "General cartaginés"] },
  ],
  entretenimiento: [
    { q: "¿Quién creó Mickey Mouse?", a: "Walt Disney", opts: ["Warner Bros", "Walt Disney", "Pixar", "DreamWorks"] },
    { q: "¿De qué país es el anime?", a: "Japón", opts: ["China", "Japón", "Corea", "Tailandia"] },
    { q: "¿Cuántas teclas tiene un piano estándar?", a: "88", opts: ["76", "88", "92", "84"] },
    { q: "¿Qué instrumento toca un violinista?", a: "Violín", opts: ["Viola", "Violín", "Chelo", "Contrabajo"] },
    { q: "¿En qué juego se capturan Pokémon?", a: "Pokémon", opts: ["Digimon", "Pokémon", "Yu-Gi-Oh", "Bakugan"] },
    { q: "¿Cuál es la red social de fotos más famosa?", a: "Instagram", opts: ["Facebook", "Instagram", "Twitter", "TikTok"] },
    { q: "¿Qué superhéroe es Bruce Wayne?", a: "Batman", opts: ["Superman", "Batman", "Spider-Man", "Iron Man"] },
    { q: "¿Quién canta 'Despacito'?", a: "Luis Fonsi", opts: ["Daddy Yankee", "Luis Fonsi", "Bad Bunny", "J Balvin"] },
    { q: "¿Qué videojuego tiene bloques y creepers?", a: "Minecraft", opts: ["Roblox", "Minecraft", "Fortnite", "Terraria"] },
    { q: "¿De qué color es Pikachu?", a: "Amarillo", opts: ["Rojo", "Amarillo", "Azul", "Verde"] },
    { q: "¿Quién interpreta a Jack Sparrow?", a: "Johnny Depp", opts: ["Orlando Bloom", "Johnny Depp", "Brad Pitt", "Tom Cruise"] },
    { q: "¿Cuántas notas musicales hay?", a: "7", opts: ["5", "7", "8", "12"] },
    { q: "¿En qué película hay un muñeco de nieve llamado Olaf?", a: "Frozen", opts: ["Frozen", "Moana", "Enredados", "Coco"] },
    { q: "¿Qué saga tiene sables de luz?", a: "Star Wars", opts: ["Star Trek", "Star Wars", "El Señor de los Anillos", "Harry Potter"] },
    { q: "¿Cuál es la consola de Nintendo más vendida?", a: "Nintendo DS", opts: ["Wii", "Nintendo DS", "Switch", "Game Boy"] },
    { q: "¿Quién es el fontanero más famoso de los videojuegos?", a: "Mario", opts: ["Luigi", "Mario", "Sonic", "Link"] },
    { q: "¿Qué película ganó el primer Óscar?", a: "Alas", opts: ["Amanecer", "Alas", "Metrópolis", "El cantor de jazz"] },
    { q: "¿De qué país son los Beatles?", a: "Inglaterra", opts: ["EEUU", "Inglaterra", "Irlanda", "Australia"] },
    { q: "¿Qué mago va a Hogwarts?", a: "Harry Potter", opts: ["Gandalf", "Harry Potter", "Merlín", "Dumbledore"] },
    { q: "¿Qué plataforma es famosa por sus bailes cortos?", a: "TikTok", opts: ["YouTube", "TikTok", "Instagram", "Snapchat"] },
    { q: "¿Cuántas películas hay de Toy Story?", a: "4", opts: ["3", "4", "5", "6"] },
    { q: "¿Qué animal es Simba?", a: "León", opts: ["Tigre", "León", "Leopardo", "Pantera"] },
    { q: "¿Quién es el creador de Facebook?", a: "Mark Zuckerberg", opts: ["Elon Musk", "Mark Zuckerberg", "Jeff Bezos", "Bill Gates"] },
    { q: "¿En qué juego se construyen fortalezas y se lucha?", a: "Fortnite", opts: ["PUBG", "Fortnite", "Apex", "Warzone"] },
    { q: "¿Qué banda cantó 'Bohemian Rhapsody'?", a: "Queen", opts: ["Beatles", "Queen", "Rolling Stones", "Pink Floyd"] },
  ],
  deporte: [
    { q: "¿Cuántos jugadores hay en un equipo de fútbol?", a: "11", opts: ["9", "11", "10", "12"] },
    { q: "¿En qué deporte se usa una raqueta y pelota amarilla?", a: "Tenis", opts: ["Bádminton", "Tenis", "Squash", "Pádel"] },
    { q: "¿Cuánto dura un partido de fútbol?", a: "90 minutos", opts: ["60 minutos", "90 minutos", "120 minutos", "80 minutos"] },
    { q: "¿En qué país se inventó el baloncesto?", a: "EE.UU.", opts: ["Canadá", "EE.UU.", "Inglaterra", "España"] },
    { q: "¿Cuántos sets hay en un partido de tenis?", a: "3 o 5", opts: ["2 o 4", "3 o 5", "4 o 6", "5 o 7"] },
    { q: "¿Qué selección ha ganado más mundiales de fútbol?", a: "Brasil", opts: ["Alemania", "Brasil", "Argentina", "Italia"] },
    { q: "¿En qué deporte se hace un 'home run'?", a: "Béisbol", opts: ["Cricket", "Béisbol", "Softball", "Golf"] },
    { q: "¿Cuánto mide una cancha de baloncesto de largo?", a: "28 metros", opts: ["25 metros", "28 metros", "30 metros", "32 metros"] },
    { q: "¿Qué deporte practica Usain Bolt?", a: "Atletismo", opts: ["Natación", "Atletismo", "Ciclismo", "Fútbol"] },
    { q: "¿Cada cuántos años se celebran los Juegos Olímpicos?", a: "4 años", opts: ["2 años", "4 años", "3 años", "5 años"] },
    { q: "¿Qué deporte se juega en Wimbledon?", a: "Tenis", opts: ["Golf", "Tenis", "Cricket", "Polo"] },
    { q: "¿Cuántos jugadores hay en un equipo de voleibol?", a: "6", opts: ["5", "6", "7", "8"] },
    { q: "¿En qué país se creó el judo?", a: "Japón", opts: ["China", "Japón", "Corea", "Brasil"] },
    { q: "¿Qué deporte usa un disco en vez de pelota?", a: "Hockey hielo", opts: ["Hockey hielo", "Lacrosse", "Polo", "Curling"] },
    { q: "¿Cuántos puntos vale un gol en fútbol?", a: "1", opts: ["1", "2", "3", "6"] },
    { q: "¿Qué nadador tiene más medallas olímpicas?", a: "Michael Phelps", opts: ["Mark Spitz", "Michael Phelps", "Ian Thorpe", "Ryan Lochte"] },
    { q: "¿En qué deporte se usa el término 'ace'?", a: "Tenis", opts: ["Golf", "Tenis", "Voleibol", "Bádminton"] },
    { q: "¿De qué país es el sumo?", a: "Japón", opts: ["China", "Japón", "Mongolia", "Corea"] },
    { q: "¿Cuántos periodos tiene un partido de hockey hielo?", a: "3", opts: ["2", "3", "4", "5"] },
    { q: "¿Qué deporte se practica en el Tour de Francia?", a: "Ciclismo", opts: ["Atletismo", "Ciclismo", "Natación", "Triatlón"] },
    { q: "¿Cuántos jugadores hay en un equipo de rugby?", a: "15", opts: ["11", "13", "15", "7"] },
    { q: "¿En qué año fue el primer Mundial de fútbol?", a: "1930", opts: ["1928", "1930", "1934", "1926"] },
    { q: "¿Qué país albergó los JJOO de 2020?", a: "Japón", opts: ["China", "Japón", "Francia", "Brasil"] },
    { q: "¿Cuántos hoyos tiene un campo de golf?", a: "18", opts: ["9", "18", "12", "24"] },
    { q: "¿Qué deporte practican los Harlem Globetrotters?", a: "Baloncesto", opts: ["Fútbol", "Baloncesto", "Béisbol", "Voleibol"] },
  ],
};