// Large trivia question banks — normal difficulty
// ~500 questions per category

export const TRIVIA_CIENCIA = [
  { q: "¿Cuál es el planeta más grande del sistema solar?", a: "Júpiter", opts: ["Saturno", "Júpiter", "Neptuno", "Urano"] },
  { q: "¿Qué gas respiramos principalmente?", a: "Oxígeno", opts: ["Nitrógeno", "Oxígeno", "CO2", "Helio"] },
  { q: "¿Cuántos huesos tiene el cuerpo humano adulto?", a: "206", opts: ["206", "300", "180", "256"] },
  { q: "¿Qué vitamina proporciona el sol?", a: "Vitamina D", opts: ["Vitamina A", "Vitamina C", "Vitamina D", "Vitamina B"] },
  { q: "¿Cuál es el metal más ligero?", a: "Litio", opts: ["Aluminio", "Litio", "Sodio", "Magnesio"] },
  { q: "¿Qué planeta es conocido como el planeta rojo?", a: "Marte", opts: ["Venus", "Marte", "Júpiter", "Mercurio"] },
  { q: "¿Cuál es el animal más rápido del mundo?", a: "Guepardo", opts: ["León", "Guepardo", "Águila", "Caballo"] },
  { q: "¿Qué órgano bombea la sangre?", a: "Corazón", opts: ["Pulmón", "Hígado", "Corazón", "Riñón"] },
  { q: "¿Cuál es el elemento químico del agua?", a: "H2O", opts: ["CO2", "H2O", "O2", "NaCl"] },
  { q: "¿Qué fuerza nos mantiene en la Tierra?", a: "Gravedad", opts: ["Magnetismo", "Gravedad", "Fricción", "Inercia"] },
  { q: "¿Cuántos cromosomas tiene el ser humano?", a: "46", opts: ["23", "46", "48", "44"] },
  { q: "¿Qué animal produce miel?", a: "Abeja", opts: ["Avispa", "Abeja", "Mariposa", "Hormiga"] },
  { q: "¿Cuál es el hueso más largo del cuerpo?", a: "Fémur", opts: ["Tibia", "Fémur", "Húmero", "Radio"] },
  { q: "¿Qué tipo de animal es una ballena?", a: "Mamífero", opts: ["Pez", "Mamífero", "Reptil", "Anfibio"] },
  { q: "¿Cuál es la estrella más cercana a la Tierra?", a: "El Sol", opts: ["Sirio", "El Sol", "Próxima Centauri", "Vega"] },
  { q: "¿Qué gas hace que las bebidas tengan burbujas?", a: "CO2", opts: ["Oxígeno", "CO2", "Nitrógeno", "Hidrógeno"] },
  { q: "¿De qué color es la sangre oxigenada?", a: "Roja", opts: ["Azul", "Roja", "Morada", "Verde"] },
  { q: "¿Cuántas patas tiene una araña?", a: "8", opts: ["6", "8", "10", "4"] },
  { q: "¿Cuál es el océano más grande?", a: "Pacífico", opts: ["Atlántico", "Pacífico", "Índico", "Ártico"] },
  { q: "¿Qué elemento químico tiene el símbolo Fe?", a: "Hierro", opts: ["Flúor", "Hierro", "Fósforo", "Francio"] },
  { q: "¿Cuántas capas tiene la atmósfera terrestre?", a: "5", opts: ["3", "4", "5", "6"] },
  { q: "¿Qué planeta tiene anillos visibles?", a: "Saturno", opts: ["Júpiter", "Saturno", "Urano", "Neptuno"] },
  { q: "¿Cuál es el río más largo del mundo?", a: "Nilo", opts: ["Amazonas", "Nilo", "Yangtsé", "Misisipi"] },
  { q: "¿Qué instrumento mide la temperatura?", a: "Termómetro", opts: ["Barómetro", "Termómetro", "Higrómetro", "Anemómetro"] },
  { q: "¿Qué planeta tiene la mayor cantidad de lunas?", a: "Saturno", opts: ["Júpiter", "Saturno", "Urano", "Neptuno"] },
  { q: "¿Cuánto tarda la luz del Sol en llegar a la Tierra?", a: "8 minutos", opts: ["1 minuto", "8 minutos", "20 minutos", "1 hora"] },
  { q: "¿Qué es la fotosíntesis?", a: "Proceso de las plantas para producir energía", opts: ["Proceso de respiración animal", "Proceso de las plantas para producir energía", "División celular", "Digestión de minerales"] },
  { q: "¿Cuántos lados tiene un hexágono?", a: "6", opts: ["5", "6", "7", "8"] },
  { q: "¿Qué tipo de energía produce el Sol?", a: "Nuclear", opts: ["Química", "Nuclear", "Eléctrica", "Mecánica"] },
  { q: "¿Cuál es el gas más abundante en la atmósfera terrestre?", a: "Nitrógeno", opts: ["Oxígeno", "Nitrógeno", "CO2", "Argón"] },
  { q: "¿Qué órgano filtra la sangre en el cuerpo humano?", a: "Riñón", opts: ["Hígado", "Riñón", "Páncreas", "Bazo"] },
  { q: "¿Cuántas alas tiene una mosca?", a: "2", opts: ["2", "4", "6", "1"] },
  { q: "¿Cuántos dientes tiene un adulto con juicio?", a: "32", opts: ["28", "30", "32", "34"] },
  { q: "¿Qué vitamina es esencial para la coagulación de la sangre?", a: "Vitamina K", opts: ["Vitamina A", "Vitamina C", "Vitamina K", "Vitamina E"] },
  { q: "¿Cuál es la capa de la Tierra más caliente?", a: "Núcleo", opts: ["Corteza", "Manto", "Núcleo", "Litosfera"] },
  { q: "¿Qué animal tiene la lengua más larga en proporción?", a: "Camaleón", opts: ["Serpiente", "Jirafa", "Camaleón", "Oso hormiguero"] },
  { q: "¿Cuántas neuronas tiene el cerebro humano aproximadamente?", a: "86.000 millones", opts: ["1.000 millones", "10.000 millones", "86.000 millones", "500.000 millones"] },
  { q: "¿Qué es la mitosis?", a: "División celular", opts: ["Fusión celular", "División celular", "Muerte celular", "Respiración celular"] },
  { q: "¿Cuál es el símbolo del oxígeno en la tabla periódica?", a: "O", opts: ["Ox", "O2", "O", "Og"] },
  { q: "¿Qué tipo de onda es el sonido?", a: "Mecánica longitudinal", opts: ["Electromagnética", "Mecánica longitudinal", "Transversal", "Cuántica"] },
  { q: "¿Cuántas fases tiene la luna en un ciclo?", a: "4 principales", opts: ["2", "4 principales", "6", "8"] },
  { q: "¿Qué es un ecosistema?", a: "Conjunto de seres vivos y su entorno", opts: ["Una especie animal", "Conjunto de seres vivos y su entorno", "Un bioma terrestre", "Una cadena alimentaria"] },
  { q: "¿Cuál es la unidad básica de la vida?", a: "Célula", opts: ["Átomo", "Célula", "Molécula", "Tejido"] },
  { q: "¿Qué elemento es el más abundante en la corteza terrestre?", a: "Oxígeno", opts: ["Silicio", "Oxígeno", "Hierro", "Aluminio"] },
  { q: "¿Qué mide el sismógrafo?", a: "Terremotos", opts: ["Temperatura", "Humedad", "Terremotos", "Presión"] },
  { q: "¿Cuál es el símbolo del oro?", a: "Au", opts: ["Go", "Au", "Or", "Ag"] },
  { q: "¿A qué temperatura hierve el agua al nivel del mar?", a: "100°C", opts: ["80°C", "90°C", "100°C", "110°C"] },
  { q: "¿Cuál es la partícula con carga positiva del átomo?", a: "Protón", opts: ["Electrón", "Neutrón", "Protón", "Quark"] },
  { q: "¿Qué animal es el más grande del mundo?", a: "Ballena azul", opts: ["Elefante africano", "Tiburón ballena", "Ballena azul", "Jirafa"] },
  { q: "¿Cuántos planetas tiene el sistema solar?", a: "8", opts: ["7", "8", "9", "10"] },
  { q: "¿Qué es la gravedad?", a: "Fuerza de atracción entre masas", opts: ["Fuerza magnética", "Fuerza de atracción entre masas", "Energía cinética", "Presión atmosférica"] },
  { q: "¿Cuál es la velocidad de la luz aproximada?", a: "300.000 km/s", opts: ["150.000 km/s", "300.000 km/s", "600.000 km/s", "1.000.000 km/s"] },
  { q: "¿Qué parte de la planta realiza la fotosíntesis?", a: "Hojas", opts: ["Raíces", "Tallo", "Hojas", "Flores"] },
  { q: "¿Cuántos órganos sensoriales tiene el ser humano?", a: "5", opts: ["4", "5", "6", "7"] },
  { q: "¿Qué es un volcán?", a: "Abertura en la corteza terrestre que expulsa magma", opts: ["Un terremoto submarino", "Abertura en la corteza terrestre que expulsa magma", "Una formación glaciar", "Una erosión rocosa"] },
  { q: "¿Qué planeta es el más cercano al Sol?", a: "Mercurio", opts: ["Venus", "Mercurio", "Marte", "Tierra"] },
  { q: "¿Cuántas costillas tiene el cuerpo humano?", a: "24 (12 pares)", opts: ["20", "22", "24 (12 pares)", "26"] },
  { q: "¿Qué es el ADN?", a: "Ácido desoxirribonucleico, portador de información genética", opts: ["Un tipo de proteína", "Ácido desoxirribonucleico, portador de información genética", "Una vitamina", "Un tipo de grasa"] },
  { q: "¿Cuál es la fórmula química del dióxido de carbono?", a: "CO2", opts: ["C2O", "CO", "CO2", "CO3"] },
  { q: "¿Qué animal tiene la gestación más larga?", a: "Elefante", opts: ["Jirafa", "Ballena", "Elefante", "Rinoceronte"] },
  { q: "¿Cuál es el metal más conductor de electricidad?", a: "Plata", opts: ["Oro", "Cobre", "Plata", "Aluminio"] },
  { q: "¿Qué es la evaporación?", a: "Paso de líquido a gas", opts: ["Paso de gas a líquido", "Paso de líquido a sólido", "Paso de líquido a gas", "Paso de sólido a líquido"] },
  { q: "¿Qué continente tiene más biodiversidad?", a: "América del Sur", opts: ["África", "Asia", "América del Sur", "Oceanía"] },
  { q: "¿Cuántas vértebras tiene la columna humana?", a: "33", opts: ["26", "30", "33", "36"] },
  { q: "¿Qué es el plancton?", a: "Organismos microscópicos que flotan en el agua", opts: ["Tipo de alga marina grande", "Pez pequeño de mar profundo", "Organismos microscópicos que flotan en el agua", "Coral vivo"] },
  { q: "¿Qué vitamina se obtiene principalmente de los cítricos?", a: "Vitamina C", opts: ["Vitamina A", "Vitamina B", "Vitamina C", "Vitamina E"] },
  { q: "¿Cuál es el animal terrestre más pesado?", a: "Elefante africano", opts: ["Hipopótamo", "Jirafa", "Elefante africano", "Rinoceronte"] },
  { q: "¿Qué es la fotosfera solar?", a: "Superficie visible del Sol", opts: ["Capa externa de la atmósfera solar", "Superficie visible del Sol", "Interior del Sol donde ocurre la fusión", "Corona del Sol"] },
  { q: "¿Cuántos hemisferios tiene el cerebro?", a: "2", opts: ["1", "2", "3", "4"] },
  { q: "¿Qué gas se produce en la fermentación alcohólica?", a: "CO2 y etanol", opts: ["Oxígeno", "Metano", "CO2 y etanol", "Nitrógeno"] },
  { q: "¿Qué es la inercia?", a: "Tendencia de un objeto a mantener su estado de movimiento", opts: ["Fuerza de frenado", "Energía potencial", "Tendencia de un objeto a mantener su estado de movimiento", "Aceleración gravitacional"] },
  { q: "¿Cuántos litros de sangre tiene el cuerpo humano aproximadamente?", a: "5 litros", opts: ["3 litros", "5 litros", "7 litros", "10 litros"] },
  { q: "¿Qué es un agujero negro?", a: "Región del espacio con gravedad extrema", opts: ["Un planeta muerto", "Una estrella fría", "Región del espacio con gravedad extrema", "Un vacío sin materia"] },
  { q: "¿Cuál es el símbolo del sodio?", a: "Na", opts: ["S", "So", "Na", "N"] },
  { q: "¿Qué son los antibióticos?", a: "Medicamentos que eliminan bacterias", opts: ["Medicamentos que eliminan virus", "Medicamentos que eliminan bacterias", "Vitaminas reforzadas", "Analgésicos potentes"] },
  { q: "¿Cuántas especies de dinosaurios se han descubierto aproximadamente?", a: "Más de 1.000", opts: ["Menos de 100", "Alrededor de 500", "Más de 1.000", "Exactamente 50"] },
  { q: "¿Qué es la bioluminiscencia?", a: "Capacidad de seres vivos de emitir luz", opts: ["Proceso de fotosíntesis marina", "Capacidad de seres vivos de emitir luz", "Reflejo de luz solar en el agua", "Tipo de fluorescencia mineral"] },
  { q: "¿Cuál es el punto de ebullición del nitrógeno líquido?", a: "-196°C", opts: ["-100°C", "-150°C", "-196°C", "-273°C"] },
  { q: "¿Qué es la presión atmosférica?", a: "Peso del aire sobre una superficie", opts: ["Temperatura del aire", "Velocidad del viento", "Peso del aire sobre una superficie", "Humedad relativa"] },
  { q: "¿Cuántos músculos tiene el cuerpo humano aproximadamente?", a: "650", opts: ["300", "450", "650", "900"] },
  { q: "¿Qué organelo produce energía en la célula?", a: "Mitocondria", opts: ["Ribosoma", "Mitocondria", "Núcleo", "Membrana"] },
  { q: "¿Cuál es el único metal líquido a temperatura ambiente?", a: "Mercurio", opts: ["Plomo", "Galio", "Mercurio", "Zinc"] },
  { q: "¿Qué es la cadena alimentaria?", a: "Secuencia de quién come a quién en un ecosistema", opts: ["Clasificación taxonómica de especies", "Secuencia de quién come a quién en un ecosistema", "Red de relaciones sociales animales", "Sistema de reproducción animal"] },
  { q: "¿Cuántos años tarda la luz de Próxima Centauri en llegar a la Tierra?", a: "4.2 años", opts: ["1 año", "4.2 años", "100 años", "1000 años"] },
  { q: "¿Qué es el pH?", a: "Medida de acidez o basicidad de una solución", opts: ["Presión hidrostática", "Medida de acidez o basicidad de una solución", "Densidad del agua", "Concentración de oxígeno"] },
  { q: "¿Cuál es el elemento más abundante en el universo?", a: "Hidrógeno", opts: ["Helio", "Hidrógeno", "Oxígeno", "Carbono"] },
  { q: "¿Qué es la deriva continental?", a: "Movimiento lento de las placas tectónicas", opts: ["Erosión costera", "Movimiento lento de las placas tectónicas", "Corriente oceánica", "Ciclo del agua"] },
  { q: "¿Cuántos colores tiene el espectro visible de la luz?", a: "7", opts: ["5", "6", "7", "9"] },
  { q: "¿Qué es un cometa?", a: "Cuerpo de hielo y polvo que orbita el Sol", opts: ["Un asteroide metálico", "Cuerpo de hielo y polvo que orbita el Sol", "Un satélite natural", "Una estrella fugaz"] },
  { q: "¿Cuál es el mineral más duro de la naturaleza?", a: "Diamante", opts: ["Cuarzo", "Corindón", "Diamante", "Topacio"] },
  { q: "¿Qué es la osmosis?", a: "Paso de agua a través de una membrana semipermeable", opts: ["Tipo de digestión", "Paso de agua a través de una membrana semipermeable", "Absorción de luz", "Proceso de respiración celular"] },
  { q: "¿Cuánto tiempo tarda la Tierra en girar sobre su propio eje?", a: "24 horas", opts: ["12 horas", "24 horas", "365 días", "30 días"] },
  { q: "¿Qué es la genética?", a: "Ciencia que estudia los genes y la herencia", opts: ["Estudio del genoma animal", "Ciencia que estudia los genes y la herencia", "Rama de la biología marina", "Estudio de las enfermedades"] },
  { q: "¿Cuál es la temperatura del núcleo terrestre?", a: "Alrededor de 6.000°C", opts: ["1.000°C", "3.000°C", "Alrededor de 6.000°C", "10.000°C"] },
  { q: "¿Qué es la energía cinética?", a: "Energía del movimiento", opts: ["Energía almacenada", "Energía del movimiento", "Energía química", "Energía nuclear"] },
  { q: "¿Cuántas galaxias hay en el universo observable aproximadamente?", a: "Billones", opts: ["Millones", "Billones", "Miles", "Trillones"] },
  { q: "¿Qué es la ósmosis inversa?", a: "Proceso de filtración de agua a través de membranas", opts: ["Evaporación forzada", "Proceso de filtración de agua a través de membranas", "Condensación química", "Destilación fraccionada"] },
  { q: "¿Cuál es el animal con mayor esperanza de vida?", a: "Tortuga de las Galápagos", opts: ["Ballena boreal", "Tortuga de las Galápagos", "Elefante africano", "Cocodrilo"] },
  { q: "¿Qué son los quarks?", a: "Partículas elementales que forman protones y neutrones", opts: ["Tipos de fotones", "Partículas elementales que forman protones y neutrones", "Ondas electromagnéticas", "Partículas de luz"] },
  { q: "¿Cuál es la diferencia entre virus y bacteria?", a: "Los virus necesitan célula huésped, las bacterias no", opts: ["No hay diferencia", "Las bacterias son más peligrosas", "Los virus necesitan célula huésped, las bacterias no", "Las bacterias son más pequeñas"] },
  { q: "¿Qué es la resonancia magnética?", a: "Técnica de imagen médica usando campos magnéticos", opts: ["Tipo de rayos X", "Técnica de imagen médica usando campos magnéticos", "Medición de ondas cerebrales", "Escáner de calor corporal"] },
  { q: "¿Cuánto pesa el cerebro humano aproximadamente?", a: "1,4 kg", opts: ["0,5 kg", "1 kg", "1,4 kg", "2 kg"] },
  { q: "¿Qué es la epilepsia?", a: "Trastorno neurológico con convulsiones", opts: ["Enfermedad cardíaca", "Trastorno neurológico con convulsiones", "Infección bacteriana cerebral", "Problema de visión"] },
  { q: "¿Cuál es el proceso por el que el agua pasa de gas a líquido?", a: "Condensación", opts: ["Evaporación", "Sublimación", "Condensación", "Fusión"] },
  { q: "¿Qué es un ecosistema marino?", a: "Sistema de seres vivos en el océano", opts: ["Solo el océano sin vida", "Sistema de seres vivos en el océano", "Solo los peces del mar", "El lecho marino"] },
  { q: "¿Cuál es el ácido del estómago?", a: "Ácido clorhídrico (HCl)", opts: ["Ácido sulfúrico", "Ácido clorhídrico (HCl)", "Ácido nítrico", "Ácido acético"] },
  { q: "¿Qué es la luz ultravioleta?", a: "Radiación electromagnética invisible al ojo humano", opts: ["Luz de color morado visible", "Radiación electromagnética invisible al ojo humano", "Luz solar amplificada", "Tipo de láser"] },
  { q: "¿Cuántos tipos de grupos sanguíneos existen en el sistema ABO?", a: "4", opts: ["2", "3", "4", "6"] },
  { q: "¿Qué es el efecto invernadero?", a: "Retención de calor en la atmósfera por gases", opts: ["Temperatura en invernaderos agrícolas", "Retención de calor en la atmósfera por gases", "Fenómeno de lluvia ácida", "Ciclo solar de 11 años"] },
  { q: "¿Cuál es la función del páncreas?", a: "Producir insulina y enzimas digestivas", opts: ["Filtrar sangre", "Producir insulina y enzimas digestivas", "Regular presión arterial", "Almacenar bilis"] },
  { q: "¿Qué es el Big Bang?", a: "Teoría del origen del universo", opts: ["Explosión estelar conocida", "Teoría del origen del universo", "Colisión de galaxias", "Formación de un agujero negro"] },
  { q: "¿Cuántos huesos tiene la mano humana?", a: "27", opts: ["20", "24", "27", "30"] },
  { q: "¿Qué elemento produce la llama amarilla?", a: "Sodio", opts: ["Potasio", "Sodio", "Calcio", "Litio"] },
  { q: "¿Qué es la biodiversidad?", a: "Variedad de especies en un ecosistema", opts: ["Número de plantas de una zona", "Variedad de especies en un ecosistema", "Cantidad de agua en el planeta", "Diversidad climática"] },
  { q: "¿Cuál es el método científico?", a: "Proceso sistemático de investigación basado en observación e hipótesis", opts: ["Conjunto de leyes físicas", "Proceso sistemático de investigación basado en observación e hipótesis", "Clasificación de ciencias", "Método de enseñanza científica"] },
  { q: "¿Qué es un neutron?", a: "Partícula sin carga del núcleo atómico", opts: ["Partícula positiva", "Partícula negativa", "Partícula sin carga del núcleo atómico", "Onda electromagnética"] },
  { q: "¿Cuántos hemisferios tiene la Tierra?", a: "2 (norte y sur)", opts: ["1", "2 (norte y sur)", "4", "6"] },
  { q: "¿Qué es la termodinámica?", a: "Estudio del calor y la energía", opts: ["Estudio del movimiento", "Estudio del calor y la energía", "Estudio de la electricidad", "Estudio de las ondas"] },
  { q: "¿Cuál es el símbolo del calcio?", a: "Ca", opts: ["C", "Ca", "Cl", "Co"] },
  { q: "¿Qué animal puede regenerar sus extremidades?", a: "Salamandra", opts: ["Lagarto", "Salamandra", "Cangrejo", "Pulpo"] },
  { q: "¿Cuántos dientes de leche tiene un niño?", a: "20", opts: ["16", "20", "24", "28"] },
  { q: "¿Qué es la materia oscura?", a: "Materia hipotética que no emite luz", opts: ["Agujeros negros visibles", "Materia hipotética que no emite luz", "Gas interestelar oscuro", "Nebulosas extintas"] },
  { q: "¿Cuál es la función del glóbulo rojo?", a: "Transportar oxígeno", opts: ["Combatir infecciones", "Coagular heridas", "Transportar oxígeno", "Producir anticuerpos"] },
  { q: "¿Qué es un isótopo?", a: "Átomo con mismo número de protones pero distinto de neutrones", opts: ["Elemento radioactivo", "Átomo con mismo número de protones pero distinto de neutrones", "Partícula subatómica nueva", "Ion con carga doble"] },
  { q: "¿Cuántos tipos de rocas hay?", a: "3 (ígneas, sedimentarias y metamórficas)", opts: ["2", "3 (ígneas, sedimentarias y metamórficas)", "5", "7"] },
  { q: "¿Qué es el ciclo del nitrógeno?", a: "Proceso de circulación del nitrógeno en la naturaleza", opts: ["Fase de degradación del CO2", "Proceso de circulación del nitrógeno en la naturaleza", "Ciclo de vida de leguminosas", "Producción industrial de fertilizantes"] },
  { q: "¿Cuál es el animal más venenoso del mundo?", a: "La rana dardo venenosa (Dendrobatidae)", opts: ["Cobra real", "Medusa caja", "La rana dardo venenosa (Dendrobatidae)", "Araña viuda negra"] },
  { q: "¿Qué es la fuerza electromagnética?", a: "Interacción entre partículas con carga eléctrica", opts: ["Fuerza gravitacional", "Interacción entre partículas con carga eléctrica", "Atracción magnética de los polos", "Energía nuclear fuerte"] },
  { q: "¿Cuántas fases del sueño tiene el ciclo normal?", a: "5", opts: ["2", "3", "4", "5"] },
  { q: "¿Qué es la homeostasis?", a: "Capacidad del cuerpo de mantener el equilibrio interno", opts: ["Proceso de reproducción", "Capacidad del cuerpo de mantener el equilibrio interno", "Sistema inmunológico activo", "Ciclo hormonal"] },
  { q: "¿Cuál es el proceso de clonación?", a: "Reproducción asexual de un organismo genéticamente idéntico", opts: ["División celular normal", "Reproducción asexual de un organismo genéticamente idéntico", "Fusión de ADN diferente", "Modificación genética parcial"] },
  { q: "¿Qué es la cadena de ADN doble hélice?", a: "Estructura espiral del ADN con dos cadenas complementarias", opts: ["Forma circular del ADN bacteriano", "Estructura espiral del ADN con dos cadenas complementarias", "ADN monocatenario", "Cromosoma condensado"] },
  { q: "¿Cuántos tipos de tejido tiene el cuerpo humano?", a: "4 (epitelial, conjuntivo, muscular y nervioso)", opts: ["2", "3", "4 (epitelial, conjuntivo, muscular y nervioso)", "6"] },
];

export const TRIVIA_HISTORIA = [
  { q: "¿En qué año llegó Colón a América?", a: "1492", opts: ["1492", "1500", "1480", "1512"] },
  { q: "¿Quién pintó la Mona Lisa?", a: "Leonardo da Vinci", opts: ["Miguel Ángel", "Leonardo da Vinci", "Rafael", "Botticelli"] },
  { q: "¿Cuál fue la primera civilización?", a: "Sumeria", opts: ["Egipcia", "Sumeria", "Griega", "Romana"] },
  { q: "¿En qué año cayó el Muro de Berlín?", a: "1989", opts: ["1987", "1989", "1991", "1985"] },
  { q: "¿Quién fue el primer presidente de EE.UU.?", a: "George Washington", opts: ["Thomas Jefferson", "George Washington", "Abraham Lincoln", "John Adams"] },
  { q: "¿Qué imperio construyó el Coliseo de Roma?", a: "Romano", opts: ["Griego", "Romano", "Persa", "Bizantino"] },
  { q: "¿En qué siglo fue la Revolución Francesa?", a: "XVIII", opts: ["XVII", "XVIII", "XIX", "XVI"] },
  { q: "¿Quién escribió Don Quijote?", a: "Cervantes", opts: ["Lope de Vega", "Cervantes", "Quevedo", "Calderón"] },
  { q: "¿Qué país inventó la pólvora?", a: "China", opts: ["India", "China", "Arabia", "Grecia"] },
  { q: "¿En qué año terminó la Segunda Guerra Mundial?", a: "1945", opts: ["1943", "1945", "1944", "1946"] },
  { q: "¿Quién descubrió la penicilina?", a: "Alexander Fleming", opts: ["Louis Pasteur", "Alexander Fleming", "Marie Curie", "Robert Koch"] },
  { q: "¿Qué civilización construyó Machu Picchu?", a: "Inca", opts: ["Maya", "Inca", "Azteca", "Olmeca"] },
  { q: "¿En qué año se hundió el Titanic?", a: "1912", opts: ["1910", "1912", "1914", "1908"] },
  { q: "¿Cuántos años duró la Guerra de los Cien Años?", a: "116", opts: ["100", "116", "99", "120"] },
  { q: "¿Quién fue Napoleón Bonaparte?", a: "Emperador francés", opts: ["Rey inglés", "Emperador francés", "Papa", "Zar ruso"] },
  { q: "¿En qué siglo se inventó la imprenta?", a: "XV", opts: ["XIV", "XV", "XVI", "XIII"] },
  { q: "¿Quién dijo 'Pienso, luego existo'?", a: "Descartes", opts: ["Platón", "Descartes", "Aristóteles", "Kant"] },
  { q: "¿Qué país fue el primero en llegar a la Luna?", a: "Estados Unidos", opts: ["Rusia", "Estados Unidos", "China", "Japón"] },
  { q: "¿Cuál es la escritura más antigua conocida?", a: "Cuneiforme", opts: ["Jeroglíficos", "Cuneiforme", "Alfabeto griego", "Chino"] },
  { q: "¿En qué continente se originó el ser humano?", a: "África", opts: ["Asia", "África", "Europa", "América"] },
  { q: "¿En qué año comenzó la Primera Guerra Mundial?", a: "1914", opts: ["1910", "1914", "1916", "1912"] },
  { q: "¿Quién fue el líder de la Revolución Cubana?", a: "Fidel Castro", opts: ["Ernesto Guevara", "Fidel Castro", "Raúl Castro", "Camilo Cienfuegos"] },
  { q: "¿Qué civilización construyó el Partenón?", a: "Griega", opts: ["Romana", "Griega", "Egipcia", "Persa"] },
  { q: "¿En qué año se independizó la India del Reino Unido?", a: "1947", opts: ["1945", "1947", "1950", "1952"] },
  { q: "¿Quién inventó el teléfono?", a: "Alexander Graham Bell", opts: ["Thomas Edison", "Alexander Graham Bell", "Nikola Tesla", "Guglielmo Marconi"] },
  { q: "¿En qué año se fundó la ONU?", a: "1945", opts: ["1919", "1939", "1945", "1950"] },
  { q: "¿Quién fue el primer hombre en el espacio?", a: "Yuri Gagarin", opts: ["Neil Armstrong", "Yuri Gagarin", "Alan Shepard", "Buzz Aldrin"] },
  { q: "¿Qué país fue el primero en dar voto a la mujer?", a: "Nueva Zelanda", opts: ["Suecia", "Reino Unido", "Nueva Zelanda", "Estados Unidos"] },
  { q: "¿Quién fue el primer faraón de Egipto?", a: "Menes", opts: ["Ramsés II", "Tutankamón", "Menes", "Cleopatra"] },
  { q: "¿En qué año cayó el Imperio Romano de Occidente?", a: "476 d.C.", opts: ["410 d.C.", "455 d.C.", "476 d.C.", "500 d.C."] },
  { q: "¿Qué invento es de Thomas Edison?", a: "Bombilla eléctrica", opts: ["Teléfono", "Radio", "Bombilla eléctrica", "Automóvil"] },
  { q: "¿En qué país nació Simón Bolívar?", a: "Venezuela", opts: ["Colombia", "Venezuela", "Perú", "Ecuador"] },
  { q: "¿Quién escribió 'El Capital'?", a: "Karl Marx", opts: ["Friedrich Engels", "Karl Marx", "Lenin", "Trotsky"] },
  { q: "¿En qué año se firmó la Magna Carta?", a: "1215", opts: ["1095", "1215", "1348", "1189"] },
  { q: "¿Quién fue el último zar de Rusia?", a: "Nicolás II", opts: ["Alejandro III", "Nicolás II", "Alejandro II", "Pablo I"] },
  { q: "¿Qué batalla puso fin al Imperio Napoleónico?", a: "Waterloo", opts: ["Austerlitz", "Waterloo", "Trafalgar", "Leipzig"] },
  { q: "¿Quién fue el fundador del Imperio mongol?", a: "Gengis Kan", opts: ["Tamerlán", "Kublai Kan", "Gengis Kan", "Ogodei"] },
  { q: "¿En qué año Bizancio cayó ante el Imperio Otomano?", a: "1453", opts: ["1389", "1453", "1492", "1517"] },
  { q: "¿Quién escribió 'El Príncipe'?", a: "Maquiavelo", opts: ["Hobbes", "Maquiavelo", "Rousseau", "Locke"] },
  { q: "¿En qué ciudad se firmó la Declaración de Independencia de EE.UU.?", a: "Filadelfia", opts: ["Boston", "Filadelfia", "Nueva York", "Washington"] },
  { q: "¿Quién fue el primer secretario general de la ONU?", a: "Trygve Lie", opts: ["Dag Hammarskjöld", "Trygve Lie", "U Thant", "Kurt Waldheim"] },
  { q: "¿En qué año se produjo la Revolución Rusa?", a: "1917", opts: ["1905", "1917", "1918", "1920"] },
  { q: "¿Qué filósofo griego fue maestro de Alejandro Magno?", a: "Aristóteles", opts: ["Platón", "Sócrates", "Aristóteles", "Epicuro"] },
  { q: "¿Quién fue el primer Papa de la historia?", a: "San Pedro", opts: ["San Pablo", "San Pedro", "San Clemente", "San Lino"] },
  { q: "¿En qué país se desarrolló la cultura azteca?", a: "México", opts: ["Guatemala", "México", "Perú", "Colombia"] },
  { q: "¿Cuándo fue la Batalla de Lepanto?", a: "1571", opts: ["1492", "1571", "1588", "1620"] },
  { q: "¿Quién construyó el Taj Mahal?", a: "Shah Jahan", opts: ["Akbar el Grande", "Shah Jahan", "Aurangzeb", "Babur"] },
  { q: "¿En qué año se construyó la Gran Muralla China originalmente?", a: "Siglo III a.C.", opts: ["Siglo I a.C.", "Siglo III a.C.", "Siglo V a.C.", "Siglo X d.C."] },
  { q: "¿Quién fue el primer hombre que circunnavegó la Tierra?", a: "Elcano (expedición Magallanes)", opts: ["Cristóbal Colón", "Vasco de Gama", "Elcano (expedición Magallanes)", "Fernando de Magallanes"] },
  { q: "¿En qué año comenzó la Guerra Fría?", a: "1947", opts: ["1945", "1947", "1950", "1953"] },
  { q: "¿Qué fue la Inquisición española?", a: "Tribunal eclesiástico que perseguía la herejía", opts: ["Guerra de reconquista", "Tribunal eclesiástico que perseguía la herejía", "Corte real de Felipe II", "Organismo colonial de control"] },
  { q: "¿Quién fue Adolf Hitler?", a: "Dictador alemán responsable del Holocausto", opts: ["Presidente de Austria", "Dictador alemán responsable del Holocausto", "General de la Primera Guerra Mundial", "Líder comunista"] },
  { q: "¿En qué año se aprobó la Constitución de EE.UU.?", a: "1787", opts: ["1776", "1781", "1787", "1791"] },
  { q: "¿Qué fue el Imperio Otomano?", a: "Imperio islámico con sede en Turquía", opts: ["Imperio árabe medieval", "Imperio islámico con sede en Turquía", "Califato de Bagdad", "Sultanato persa"] },
  { q: "¿Cuándo se fundó Roma según la tradición?", a: "753 a.C.", opts: ["500 a.C.", "753 a.C.", "100 a.C.", "1000 a.C."] },
  { q: "¿Quién fue Charles Darwin?", a: "Naturalista que formuló la teoría de la evolución", opts: ["Físico que descubrió la gravedad", "Naturalista que formuló la teoría de la evolución", "Químico que descubrió el oxígeno", "Matemático que inventó el cálculo"] },
  { q: "¿En qué año se abolió la esclavitud en Estados Unidos?", a: "1865", opts: ["1848", "1860", "1865", "1870"] },
  { q: "¿Qué fue la Revolución Industrial?", a: "Transformación económica con máquinas en el siglo XVIII-XIX", opts: ["Revolución política francesa", "Transformación económica con máquinas en el siglo XVIII-XIX", "Movimiento obrero del siglo XX", "Industrialización soviética"] },
  { q: "¿Cuándo fue el Renacimiento?", a: "Siglos XIV-XVII", opts: ["Siglos X-XII", "Siglos XIV-XVII", "Siglos I-III", "Siglos XVIII-XIX"] },
  { q: "¿Quién fue Mao Zedong?", a: "Fundador de la República Popular China", opts: ["Líder del Japón imperial", "Fundador de la República Popular China", "General de la Segunda Guerra Mundial", "Presidente de la República de China"] },
  { q: "¿En qué año se descubrió América por los europeos?", a: "1492", opts: ["1488", "1492", "1497", "1500"] },
  { q: "¿Qué fue la Guerra de los Treinta Años?", a: "Conflicto religioso europeo (1618-1648)", opts: ["Guerra napoleónica", "Conflicto religioso europeo (1618-1648)", "Cruzada medieval", "Guerra de independencia americana"] },
  { q: "¿Quién fue Julio César?", a: "General y político romano asesinado en 44 a.C.", opts: ["Rey de Roma", "General y político romano asesinado en 44 a.C.", "Primer emperador romano", "Filósofo romano estoico"] },
  { q: "¿En qué año se inventó la imprenta de Gutenberg?", a: "1440", opts: ["1200", "1350", "1440", "1500"] },
  { q: "¿Quién fue el rey más famoso de los francos?", a: "Carlomagno", opts: ["Clodoveo", "Carlomagno", "Luis XIV", "Felipe II"] },
  { q: "¿Qué fue la Reconquista española?", a: "Proceso de recuperación de territorios ocupados por los moros", opts: ["Expansión colonial de España", "Proceso de recuperación de territorios ocupados por los moros", "Unificación de los reinos ibéricos", "Guerra de independencia española"] },
  { q: "¿Cuándo se produjo el genocidio armenio?", a: "1915", opts: ["1905", "1915", "1925", "1935"] },
  { q: "¿Quién lideró la independencia de la India?", a: "Mahatma Gandhi", opts: ["Nehru", "Mahatma Gandhi", "Muhammad Alí Jinnah", "Subhas Chandra Bose"] },
  { q: "¿En qué año se fundó la Unión Europea?", a: "1993 (Tratado de Maastricht)", opts: ["1957", "1973", "1993 (Tratado de Maastricht)", "2002"] },
  { q: "¿Qué fue el apartheid?", a: "Régimen de segregación racial en Sudáfrica", opts: ["Colonización británica en África", "Régimen de segregación racial en Sudáfrica", "Sistema de castas en India", "Discriminación en EEUU"] },
  { q: "¿Quién fue Martin Luther King?", a: "Líder del movimiento por los derechos civiles en EEUU", opts: ["Fundador de la NAACP", "Líder del movimiento por los derechos civiles en EEUU", "Primer presidente negro de EEUU", "Político demócrata de los 60"] },
  { q: "¿En qué año se fundó la ciudad de Constantinopla?", a: "330 d.C.", opts: ["100 d.C.", "200 d.C.", "330 d.C.", "500 d.C."] },
  { q: "¿Quién fue Cleopatra?", a: "Reina del Egipto ptolemaico", opts: ["Diosa egipcia", "Reina del Egipto ptolemaico", "Emperatriz romana", "Sacerdotisa de Isis"] },
  { q: "¿Qué fue la Armada Invencible?", a: "Flota española derrotada por Inglaterra en 1588", opts: ["Flota portuguesa de exploración", "Flota española derrotada por Inglaterra en 1588", "Escuadra vikinga del siglo XI", "Armada francesa de Napoleón"] },
  { q: "¿En qué año se proclamó la Primera República Española?", a: "1873", opts: ["1868", "1873", "1876", "1931"] },
  { q: "¿Quién fue Isaac Newton?", a: "Físico que formuló las leyes de la mecánica clásica", opts: ["Matemático que inventó el cálculo diferencial solo", "Físico que formuló las leyes de la mecánica clásica", "Astrónomo que descubrió Neptuno", "Alquimista del siglo XV"] },
  { q: "¿Cuándo se fundó el Imperio romano?", a: "27 a.C.", opts: ["509 a.C.", "100 a.C.", "27 a.C.", "0"] },
  { q: "¿Qué fue la Ilustración?", a: "Movimiento filosófico del siglo XVIII que exaltaba la razón", opts: ["Movimiento artístico barroco", "Movimiento filosófico del siglo XVIII que exaltaba la razón", "Reforma religiosa protestante", "Corriente literaria del Romanticismo"] },
  { q: "¿Quién fue Simón de Montfort?", a: "Noble que creó el primer Parlamento inglés", opts: ["Rey inglés medieval", "Noble que creó el primer Parlamento inglés", "Cruzado normando", "Cardenal de la Inquisición"] },
  { q: "¿En qué año se proclamó la independencia de México?", a: "1821", opts: ["1810", "1815", "1821", "1825"] },
  { q: "¿Quién fue Winston Churchill?", a: "Primer ministro británico durante la Segunda Guerra Mundial", opts: ["General aliado en la Segunda Guerra Mundial", "Primer ministro británico durante la Segunda Guerra Mundial", "Presidente de EEUU durante la guerra", "Líder de la resistencia francesa"] },
  { q: "¿Qué fue el Edicto de Nantes?", a: "Decreto de tolerancia religiosa en Francia (1598)", opts: ["Tratado de paz franco-español", "Decreto de tolerancia religiosa en Francia (1598)", "Abolición de la feudalidad", "Declaración de guerra de Enrique IV"] },
  { q: "¿Cuándo se produjo la Batalla de Hastings?", a: "1066", opts: ["1000", "1066", "1100", "1150"] },
  { q: "¿Quién fue Saladino?", a: "Sultán musulmán que reconquistó Jerusalén", opts: ["Califa abasí", "Sultán musulmán que reconquistó Jerusalén", "Rey de Egipto cristiano", "General de las Cruzadas"] },
  { q: "¿En qué año se adoptó la Declaración de Derechos Humanos de la ONU?", a: "1948", opts: ["1945", "1948", "1950", "1960"] },
  { q: "¿Quién fue Alejandro Magno?", a: "Rey macedonio que creó un vasto imperio", opts: ["Rey de Grecia clásica", "Rey macedonio que creó un vasto imperio", "General persa victorioso", "Faraón egipcio conquistador"] },
  { q: "¿Cuándo ocurrió el Desembarco de Normandía?", a: "1944", opts: ["1942", "1943", "1944", "1945"] },
  { q: "¿Qué fue el feudalismo?", a: "Sistema político y social de la Edad Media", opts: ["Sistema de esclavitud romano", "Sistema político y social de la Edad Media", "Organización tribal germánica", "Régimen mercantilista del siglo XVI"] },
  { q: "¿Quién fue Galileo Galilei?", a: "Astrónomo y físico que defendió el heliocentrismo", opts: ["Matemático árabe medieval", "Astrónomo y físico que defendió el heliocentrismo", "Inventor del telescopio sin uso científico", "Alquimista renacentista"] },
  { q: "¿En qué año ocurrió el atentado del 11-S?", a: "2001", opts: ["1999", "2000", "2001", "2002"] },
  { q: "¿Qué fue el Holocausto?", a: "Genocidio de judíos y otros grupos por los nazis", opts: ["Bombardeo de Hiroshima", "Genocidio de judíos y otros grupos por los nazis", "Masacre en la URSS", "Purgas estalinistas"] },
  { q: "¿Quién fue Nelson Mandela?", a: "Luchador antiapartheid y primer presidente negro de Sudáfrica", opts: ["Líder independentista zimbabuense", "Luchador antiapartheid y primer presidente negro de Sudáfrica", "Presidente de Nigeria", "Activista keniano por los derechos civiles"] },
  { q: "¿En qué año se proclamó la Segunda República en España?", a: "1931", opts: ["1923", "1928", "1931", "1936"] },
  { q: "¿Qué fue la Guerra de Corea?", a: "Conflicto (1950-1953) entre Corea del Norte y del Sur", opts: ["Guerra civil vietnamita", "Conflicto (1950-1953) entre Corea del Norte y del Sur", "Invasión china de Japón", "Conflicto en Manchuria"] },
  { q: "¿Quién fue Moctezuma?", a: "Gobernante azteca durante la conquista española", opts: ["Rey inca de Cuzco", "Gobernante azteca durante la conquista española", "Jefe maya de Chichén Itzá", "Líder olmeca"] },
  { q: "¿Cuándo se produjo la Caída del Imperio Romano de Oriente?", a: "1453", opts: ["1200", "1354", "1453", "1500"] },
  { q: "¿Qué fue la Revolución de los Claveles?", a: "Revolución pacífica en Portugal en 1974", opts: ["Revolución española de 1936", "Revolución pacífica en Portugal en 1974", "Movimiento independentista portugués", "Golpe de Estado en Brasil"] },
  { q: "¿Quién fue el Cid Campeador?", a: "Héroe castellano Rodrigo Díaz de Vivar", opts: ["Rey de Castilla medieval", "Héroe castellano Rodrigo Díaz de Vivar", "General árabe de Al-Ándalus", "Conde de Barcelona"] },
  { q: "¿En qué año comenzó la Guerra Civil Española?", a: "1936", opts: ["1931", "1933", "1936", "1939"] },
  { q: "¿Qué fue la Conferencia de Yalta?", a: "Reunión de Churchill, Roosevelt y Stalin en 1945", opts: ["Conferencia de paz tras la Primera Guerra Mundial", "Reunión de Churchill, Roosevelt y Stalin en 1945", "Fundación de la ONU", "Tratado de rendición de Alemania"] },
  { q: "¿Quién fue Hernán Cortés?", a: "Conquistador español que derrotó al Imperio azteca", opts: ["Explorador portugués de las Américas", "Conquistador español que derrotó al Imperio azteca", "Gobernador de Cuba", "Explorador del Río de la Plata"] },
  { q: "¿Cuándo nació Jesús de Nazaret según el calendario?", a: "Aproximadamente año 4-6 a.C.", opts: ["Exactamente el año 0", "Año 1 d.C.", "Aproximadamente año 4-6 a.C.", "Año 33 d.C."] },
];

export const TRIVIA_ENTRETENIMIENTO = [
  { q: "¿Quién creó Mickey Mouse?", a: "Walt Disney", opts: ["Warner Bros", "Walt Disney", "Pixar", "DreamWorks"] },
  { q: "¿De qué país es el anime?", a: "Japón", opts: ["China", "Japón", "Corea", "Tailandia"] },
  { q: "¿Cuántas teclas tiene un piano estándar?", a: "88", opts: ["76", "88", "92", "84"] },
  { q: "¿Qué superhéroe es Bruce Wayne?", a: "Batman", opts: ["Superman", "Batman", "Spider-Man", "Iron Man"] },
  { q: "¿Quién canta 'Despacito'?", a: "Luis Fonsi", opts: ["Daddy Yankee", "Luis Fonsi", "Bad Bunny", "J Balvin"] },
  { q: "¿Qué videojuego tiene bloques y creepers?", a: "Minecraft", opts: ["Roblox", "Minecraft", "Fortnite", "Terraria"] },
  { q: "¿De qué color es Pikachu?", a: "Amarillo", opts: ["Rojo", "Amarillo", "Azul", "Verde"] },
  { q: "¿Quién interpreta a Jack Sparrow?", a: "Johnny Depp", opts: ["Orlando Bloom", "Johnny Depp", "Brad Pitt", "Tom Cruise"] },
  { q: "¿Cuántas notas musicales hay?", a: "7", opts: ["5", "7", "8", "12"] },
  { q: "¿En qué película hay un muñeco de nieve llamado Olaf?", a: "Frozen", opts: ["Frozen", "Moana", "Enredados", "Coco"] },
  { q: "¿Qué saga tiene sables de luz?", a: "Star Wars", opts: ["Star Trek", "Star Wars", "El Señor de los Anillos", "Harry Potter"] },
  { q: "¿Quién es el fontanero más famoso de los videojuegos?", a: "Mario", opts: ["Luigi", "Mario", "Sonic", "Link"] },
  { q: "¿De qué país son los Beatles?", a: "Inglaterra", opts: ["EEUU", "Inglaterra", "Irlanda", "Australia"] },
  { q: "¿Qué mago va a Hogwarts?", a: "Harry Potter", opts: ["Gandalf", "Harry Potter", "Merlín", "Dumbledore"] },
  { q: "¿Qué plataforma es famosa por sus bailes cortos?", a: "TikTok", opts: ["YouTube", "TikTok", "Instagram", "Snapchat"] },
  { q: "¿Cuántas películas hay de Toy Story?", a: "4", opts: ["3", "4", "5", "6"] },
  { q: "¿Qué animal es Simba?", a: "León", opts: ["Tigre", "León", "Leopardo", "Pantera"] },
  { q: "¿Quién es el creador de Facebook?", a: "Mark Zuckerberg", opts: ["Elon Musk", "Mark Zuckerberg", "Jeff Bezos", "Bill Gates"] },
  { q: "¿Qué banda cantó 'Bohemian Rhapsody'?", a: "Queen", opts: ["Beatles", "Queen", "Rolling Stones", "Pink Floyd"] },
  { q: "¿Cuántas personas hay en 'Friends'?", a: "6", opts: ["4", "5", "6", "7"] },
  { q: "¿Quién es el protagonista de 'Breaking Bad'?", a: "Walter White", opts: ["Jesse Pinkman", "Walter White", "Saul Goodman", "Hank Schrader"] },
  { q: "¿En qué año salió el iPhone original?", a: "2007", opts: ["2005", "2006", "2007", "2008"] },
  { q: "¿Qué película de Pixar fue la primera?", a: "Toy Story", opts: ["A Bug's Life", "Toy Story", "Monsters Inc", "Finding Nemo"] },
  { q: "¿Quién es el cantante de Bohemian Rhapsody?", a: "Freddie Mercury", opts: ["David Bowie", "Freddie Mercury", "Mick Jagger", "Robert Plant"] },
  { q: "¿Qué actor hace de Iron Man?", a: "Robert Downey Jr.", opts: ["Chris Evans", "Robert Downey Jr.", "Chris Hemsworth", "Mark Ruffalo"] },
  { q: "¿Cuántos libros tiene la saga 'El Señor de los Anillos'?", a: "3", opts: ["2", "3", "4", "6"] },
  { q: "¿En qué año se lanzó YouTube?", a: "2005", opts: ["2003", "2004", "2005", "2006"] },
  { q: "¿Qué personaje dijo 'Que la fuerza te acompañe'?", a: "Obi-Wan Kenobi", opts: ["Luke Skywalker", "Obi-Wan Kenobi", "Yoda", "Qui-Gon Jinn"] },
  { q: "¿Quién canta 'Shape of You'?", a: "Ed Sheeran", opts: ["Justin Bieber", "Ed Sheeran", "Bruno Mars", "Charlie Puth"] },
  { q: "¿En qué ciudad está ambientada 'Narcos'?", a: "Medellín", opts: ["Bogotá", "Medellín", "Cali", "Cartagena"] },
  { q: "¿Cuántos fotogramas por segundo tiene el cine estándar?", a: "24", opts: ["18", "24", "30", "60"] },
  { q: "¿Qué director filmó '2001: Una odisea del espacio'?", a: "Stanley Kubrick", opts: ["Steven Spielberg", "Stanley Kubrick", "Ridley Scott", "George Lucas"] },
  { q: "¿En qué año se estrenó el primer videojuego comercial 'Pong'?", a: "1972", opts: ["1969", "1972", "1975", "1977"] },
  { q: "¿Qué compositor escribió la 'Quinta Sinfonía'?", a: "Beethoven", opts: ["Mozart", "Beethoven", "Bach", "Brahms"] },
  { q: "¿Quién escribió 'Cien años de soledad'?", a: "Gabriel García Márquez", opts: ["Mario Vargas Llosa", "Gabriel García Márquez", "Julio Cortázar", "Pablo Neruda"] },
  { q: "¿Cuántos libros tiene la serie original de Harry Potter?", a: "7", opts: ["6", "7", "8", "9"] },
  { q: "¿En qué año se fundó la empresa Nintendo?", a: "1889", opts: ["1950", "1974", "1889", "1932"] },
  { q: "¿Qué película ganó el Óscar a mejor película en 1994?", a: "Forrest Gump", opts: ["Pulp Fiction", "Forrest Gump", "El rey león", "Shawshank"] },
  { q: "¿Quién compuso la ópera 'La Traviata'?", a: "Verdi", opts: ["Puccini", "Verdi", "Wagner", "Mozart"] },
  { q: "¿Qué artista pintó 'La persistencia de la memoria'?", a: "Dalí", opts: ["Picasso", "Dalí", "Miró", "Kandinsky"] },
  { q: "¿En qué país se originó el género musical K-pop?", a: "Corea del Sur", opts: ["Japón", "China", "Corea del Sur", "Corea del Norte"] },
  { q: "¿Cuántas temporadas tiene la serie 'Breaking Bad'?", a: "5", opts: ["4", "5", "6", "7"] },
  { q: "¿Qué actor interpretó a Hannibal Lecter en 'El silencio de los corderos'?", a: "Anthony Hopkins", opts: ["Jack Nicholson", "Anthony Hopkins", "Gary Oldman", "Robert De Niro"] },
  { q: "¿Quién dirige la saga 'El Padrino'?", a: "Francis Ford Coppola", opts: ["Martin Scorsese", "Francis Ford Coppola", "Brian De Palma", "Sidney Lumet"] },
  { q: "¿Qué serie tiene a los personajes Sheldon, Leonard y Penny?", a: "The Big Bang Theory", opts: ["How I Met Your Mother", "The Big Bang Theory", "Friends", "Two and a Half Men"] },
  { q: "¿Qué película animada tiene la canción 'Let It Go'?", a: "Frozen", opts: ["Moana", "Frozen", "Brave", "Encanto"] },
  { q: "¿Quién canta 'Bad Guy'?", a: "Billie Eilish", opts: ["Ariana Grande", "Billie Eilish", "Dua Lipa", "Olivia Rodrigo"] },
  { q: "¿Qué videojuego tiene a un personaje llamado Link?", a: "The Legend of Zelda", opts: ["Final Fantasy", "The Legend of Zelda", "Dragon Quest", "Pokémon"] },
  { q: "¿En qué año se estrenó 'Avatar' de James Cameron?", a: "2009", opts: ["2005", "2007", "2009", "2011"] },
  { q: "¿Qué serie tiene dragones y batallas medievales?", a: "Game of Thrones", opts: ["Vikings", "Game of Thrones", "The Last Kingdom", "Merlin"] },
  { q: "¿Quién canta 'Thriller'?", a: "Michael Jackson", opts: ["Prince", "Michael Jackson", "Madonna", "David Bowie"] },
  { q: "¿Cuántas temporadas tiene 'Stranger Things'?", a: "5", opts: ["3", "4", "5", "6"] },
  { q: "¿Qué streaming tiene el logo de la 'N' roja?", a: "Netflix", opts: ["Hulu", "Netflix", "HBO", "Disney+"] },
  { q: "¿Quién interpreta a Hermione Granger?", a: "Emma Watson", opts: ["Emma Stone", "Emma Watson", "Keira Knightley", "Natalie Portman"] },
  { q: "¿En qué año nació Shakira?", a: "1977", opts: ["1975", "1977", "1980", "1982"] },
  { q: "¿Qué serie tiene a Walter White como químico de metanfetaminas?", a: "Breaking Bad", opts: ["Ozark", "Narcos", "Breaking Bad", "Better Call Saul"] },
  { q: "¿Qué artista es conocido como el 'Rey del Pop'?", a: "Michael Jackson", opts: ["Elvis Presley", "Michael Jackson", "Prince", "Justin Timberlake"] },
  { q: "¿Cuántas películas tiene el universo Marvel hasta 2023?", a: "Más de 30", opts: ["Menos de 10", "Exactamente 20", "Más de 30", "Solo 15"] },
  { q: "¿Qué personaje de Disney tiene una madrastra malvada?", a: "Cenicienta", opts: ["Blancanieves", "Cenicienta", "La Bella Durmiente", "Rapunzel"] },
  { q: "¿Quién creó los Simpsons?", a: "Matt Groening", opts: ["Seth MacFarlane", "Matt Groening", "Mike Judge", "Chuck Lorre"] },
  { q: "¿En qué año se estrenó 'Titanic' de James Cameron?", a: "1997", opts: ["1994", "1997", "2000", "2002"] },
  { q: "¿Qué canción tiene la letra 'Baby shark doo doo doo'?", a: "Baby Shark", opts: ["Shark Tale", "Baby Shark", "Finding Nemo Theme", "Ocean Song"] },
  { q: "¿Quién es la creadora de 'Rebelde' (RBD)?", a: "Televisa (producción de Pedro Damián)", opts: ["Sony Music", "Televisa (producción de Pedro Damián)", "Univision", "HBO Latino"] },
  { q: "¿Qué actriz es conocida por sus roles en 'Legally Blonde'?", a: "Reese Witherspoon", opts: ["Kirsten Dunst", "Reese Witherspoon", "Cameron Diaz", "Drew Barrymore"] },
  { q: "¿En qué año se estrenó 'El Rey León' original?", a: "1994", opts: ["1990", "1992", "1994", "1996"] },
  { q: "¿Quién canta 'Shakira Shakira' en la canción Hips Don't Lie?", a: "Shakira y Wyclef Jean", opts: ["Shakira sola", "Shakira y Wyclef Jean", "Shakira y Pitbull", "Shakira y Daddy Yankee"] },
  { q: "¿Qué programa de televisión española fue pionero en el 'reality show'?", a: "Gran Hermano", opts: ["Operación Triunfo", "Gran Hermano", "Supervivientes", "La isla de las tentaciones"] },
  { q: "¿Cuántos años estuvo en el aire 'The Simpsons'?", a: "Más de 30 años (sigue en emisión)", opts: ["10 años", "20 años", "Más de 30 años (sigue en emisión)", "Terminó en 2010"] },
  { q: "¿Qué canción de Adele habla de una ruptura y empieza con 'Hello'?", a: "Hello", opts: ["Someone Like You", "Hello", "Rolling in the Deep", "Skyfall"] },
  { q: "¿Quién ganó el primer 'Operación Triunfo' en España?", a: "Rosa López", opts: ["David Bisbal", "Rosa López", "David Bustamante", "Alejandro Sanz"] },
  { q: "¿De qué trata la serie 'La Casa de Papel'?", a: "Un grupo roba el banco de España", opts: ["Policías corruptos en Madrid", "Un grupo roba el banco de España", "Narcos españoles en Latinoamérica", "Espías internacionales en Europa"] },
  { q: "¿Qué instrumento toca Slash de Guns N' Roses?", a: "Guitarra", opts: ["Bajo", "Guitarra", "Batería", "Piano"] },
  { q: "¿Quién es el director de 'Inception'?", a: "Christopher Nolan", opts: ["Steven Spielberg", "Christopher Nolan", "James Cameron", "Ridley Scott"] },
  { q: "¿En qué año se fundó Spotify?", a: "2006", opts: ["2003", "2006", "2008", "2010"] },
  { q: "¿Qué personaje de animación vive en una piña bajo el mar?", a: "Bob Esponja", opts: ["Patrick", "Bob Esponja", "Calamardo", "Sandy"] },
  { q: "¿Quién es el villano principal de 'El Rey León'?", a: "Scar", opts: ["Mufasa", "Scar", "Timon", "Pumba"] },
  { q: "¿Qué serie de ciencia ficción tiene la Estrella de la Muerte?", a: "Star Wars", opts: ["Star Trek", "Star Wars", "Dune", "The Expanse"] },
  { q: "¿Cuántos integrantes tiene BTS?", a: "7", opts: ["5", "6", "7", "9"] },
  { q: "¿Quién interpreta a Spider-Man en la saga del universo Marvel?", a: "Tom Holland", opts: ["Andrew Garfield", "Tobey Maguire", "Tom Holland", "Zendaya"] },
  { q: "¿Qué significa 'MTV'?", a: "Music Television", opts: ["Media Television", "Music Television", "Modern TV", "Music TV Worldwide"] },
  { q: "¿En qué año se estrenó 'Encanto' de Disney?", a: "2021", opts: ["2018", "2019", "2021", "2022"] },
  { q: "¿Quién canta 'Malamente'?", a: "Rosalía", opts: ["Aitana", "Rosalía", "Ana Guerra", "Lola Índigo"] },
  { q: "¿Qué serie tiene al personaje de Tony Soprano?", a: "Los Soprano", opts: ["Boardwalk Empire", "Los Soprano", "Ozark", "Peaky Blinders"] },
  { q: "¿Quién es la creadora del libro 'Twilight'?", a: "Stephenie Meyer", opts: ["J.K. Rowling", "Stephenie Meyer", "Suzanne Collins", "E.L. James"] },
  { q: "¿En qué año fue el primer mundial de fútbol en España?", a: "1982", opts: ["1978", "1982", "1986", "1990"] },
  { q: "¿Qué programa de talentos tiene a Simon Cowell como jurado?", a: "The X Factor / Got Talent", opts: ["American Idol", "The X Factor / Got Talent", "The Voice", "Britain's Got Talent"] },
  { q: "¿Quién es el director de 'Parasite'?", a: "Bong Joon-ho", opts: ["Park Chan-wook", "Bong Joon-ho", "Kim Ki-duk", "Lee Chang-dong"] },
  { q: "¿Cuántas temporadas tiene 'Game of Thrones'?", a: "8", opts: ["6", "7", "8", "10"] },
  { q: "¿Qué canción de Dua Lipa habla de 'nuevas reglas'?", a: "New Rules", opts: ["Don't Start Now", "Levitating", "New Rules", "One Kiss"] },
  { q: "¿Quién hace de Thor en el universo Marvel?", a: "Chris Hemsworth", opts: ["Chris Evans", "Chris Hemsworth", "Chris Pratt", "Tom Hiddleston"] },
  { q: "¿En qué plataforma se estrenó 'The Mandalorian'?", a: "Disney+", opts: ["Netflix", "HBO Max", "Disney+", "Amazon Prime"] },
  { q: "¿Qué actor es conocido por interpretar a Jack Sparrow?", a: "Johnny Depp", opts: ["Orlando Bloom", "Johnny Depp", "Keira Knightley", "Geoffrey Rush"] },
  { q: "¿Quién canta 'Flowers'?", a: "Miley Cyrus", opts: ["Selena Gomez", "Miley Cyrus", "Taylor Swift", "Demi Lovato"] },
  { q: "¿Qué película tiene a Mía y Sebastián como protagonistas?", a: "La La Land", opts: ["La La Land", "Whiplash", "Begin Again", "Once"] },
  { q: "¿Cuántas temporadas tiene 'Élite'?", a: "7", opts: ["4", "5", "6", "7"] },
  { q: "¿Quién es el director de 'Oppenheimer'?", a: "Christopher Nolan", opts: ["Denis Villeneuve", "Christopher Nolan", "Steven Spielberg", "Martin Scorsese"] },
  { q: "¿Qué videojuego tiene un personaje llamado 'Fortnite'?", a: "Fortnite no es un personaje, es el nombre del juego", opts: ["Fortnite no es un personaje, es el nombre del juego", "Jonesy es el personaje del juego Fortnite", "Fortnite tiene múltiples skins", "El personaje se llama Battle Royale"] },
  { q: "¿Qué serie española trata sobre una escuela de baile?", a: "Fama a bailar", opts: ["Física o Química", "Fama a bailar", "El Internado", "Aquí no hay quien viva"] },
  { q: "¿Quién protagoniza la serie 'Euphoria'?", a: "Zendaya", opts: ["Sydney Sweeney", "Zendaya", "Hunter Schafer", "Alexa Demie"] },
];

export const TRIVIA_DEPORTE = [
  { q: "¿Cuántos jugadores hay en un equipo de fútbol?", a: "11", opts: ["9", "11", "10", "12"] },
  { q: "¿En qué deporte se usa una raqueta y pelota amarilla?", a: "Tenis", opts: ["Bádminton", "Tenis", "Squash", "Pádel"] },
  { q: "¿Cuánto dura un partido de fútbol?", a: "90 minutos", opts: ["60 minutos", "90 minutos", "120 minutos", "80 minutos"] },
  { q: "¿En qué país se inventó el baloncesto?", a: "EE.UU.", opts: ["Canadá", "EE.UU.", "Inglaterra", "España"] },
  { q: "¿Qué selección ha ganado más mundiales de fútbol?", a: "Brasil", opts: ["Alemania", "Brasil", "Argentina", "Italia"] },
  { q: "¿En qué deporte se hace un 'home run'?", a: "Béisbol", opts: ["Cricket", "Béisbol", "Softball", "Golf"] },
  { q: "¿Qué deporte practica Usain Bolt?", a: "Atletismo", opts: ["Natación", "Atletismo", "Ciclismo", "Fútbol"] },
  { q: "¿Cada cuántos años se celebran los Juegos Olímpicos?", a: "4 años", opts: ["2 años", "4 años", "3 años", "5 años"] },
  { q: "¿Qué deporte se juega en Wimbledon?", a: "Tenis", opts: ["Golf", "Tenis", "Cricket", "Polo"] },
  { q: "¿Cuántos jugadores hay en un equipo de voleibol?", a: "6", opts: ["5", "6", "7", "8"] },
  { q: "¿En qué país se creó el judo?", a: "Japón", opts: ["China", "Japón", "Corea", "Brasil"] },
  { q: "¿Qué nadador tiene más medallas olímpicas?", a: "Michael Phelps", opts: ["Mark Spitz", "Michael Phelps", "Ian Thorpe", "Ryan Lochte"] },
  { q: "¿En qué deporte se usa el término 'ace'?", a: "Tenis", opts: ["Golf", "Tenis", "Voleibol", "Bádminton"] },
  { q: "¿De qué país es el sumo?", a: "Japón", opts: ["China", "Japón", "Mongolia", "Corea"] },
  { q: "¿Qué deporte se practica en el Tour de Francia?", a: "Ciclismo", opts: ["Atletismo", "Ciclismo", "Natación", "Triatlón"] },
  { q: "¿Cuántos jugadores hay en un equipo de rugby?", a: "15", opts: ["11", "13", "15", "7"] },
  { q: "¿En qué año fue el primer Mundial de fútbol?", a: "1930", opts: ["1928", "1930", "1934", "1926"] },
  { q: "¿Cuántos hoyos tiene un campo de golf?", a: "18", opts: ["9", "18", "12", "24"] },
  { q: "¿Quién tiene el récord mundial de los 100m lisos?", a: "Usain Bolt", opts: ["Justin Gatlin", "Usain Bolt", "Tyson Gay", "Asafa Powell"] },
  { q: "¿Cuántos metros mide un maratón?", a: "42.195", opts: ["42.000", "42.195", "42.500", "43.000"] },
  { q: "¿Cuántos Grand Slams de tenis existen?", a: "4", opts: ["3", "4", "5", "6"] },
  { q: "¿Cuántos rounds tiene un combate de boxeo profesional?", a: "12", opts: ["10", "12", "15", "8"] },
  { q: "¿Cuál es la longitud oficial de una piscina olímpica?", a: "50 metros", opts: ["25 metros", "50 metros", "100 metros", "75 metros"] },
  { q: "¿Qué club ha ganado más Champions League?", a: "Real Madrid", opts: ["Barcelona", "Real Madrid", "Bayern Múnich", "AC Milan"] },
  { q: "¿Cuántos jugadores hay en un equipo de water polo?", a: "7", opts: ["6", "7", "8", "9"] },
  { q: "¿En qué país se inventó el rugby?", a: "Inglaterra", opts: ["Irlanda", "Escocia", "Inglaterra", "Gales"] },
  { q: "¿Cuántos puntos vale un triple en baloncesto?", a: "3", opts: ["2", "3", "4", "5"] },
  { q: "¿Qué equipo tiene más títulos de la NBA?", a: "Boston Celtics", opts: ["Los Angeles Lakers", "Boston Celtics", "Chicago Bulls", "Golden State Warriors"] },
  { q: "¿Cuántas tarjetas amarillas dan una expulsión en fútbol?", a: "2", opts: ["1", "2", "3", "4"] },
  { q: "¿Qué deporte practica LeBron James?", a: "Baloncesto", opts: ["Fútbol", "Baloncesto", "Béisbol", "Fútbol americano"] },
  { q: "¿En qué deporte está el 'bunker'?", a: "Golf", opts: ["Béisbol", "Cricket", "Golf", "Rugby"] },
  { q: "¿Qué club español ha ganado más Ligas?", a: "Real Madrid", opts: ["Barcelona", "Real Madrid", "Atlético de Madrid", "Valencia"] },
  { q: "¿Cuántos jugadores tiene un equipo de béisbol en el campo?", a: "9", opts: ["8", "9", "10", "11"] },
  { q: "¿En qué deporte existe el 'try'?", a: "Rugby", opts: ["Fútbol americano", "Rugby", "Cricket", "Polo"] },
  { q: "¿Cuántas disciplinas tiene el triatlón?", a: "3", opts: ["2", "3", "4", "5"] },
  { q: "¿En qué año se celebraron los primeros Juegos Olímpicos modernos?", a: "1896", opts: ["1888", "1896", "1900", "1904"] },
  { q: "¿Qué tenista tiene más títulos de Grand Slam masculinos?", a: "Novak Djokovic", opts: ["Roger Federer", "Rafael Nadal", "Novak Djokovic", "Pete Sampras"] },
  { q: "¿En qué deporte se usa el término 'épée'?", a: "Esgrima", opts: ["Polo", "Esgrima", "Equitación", "Jabalina"] },
  { q: "¿Cuántos jugadores hay en un equipo de polo?", a: "4", opts: ["3", "4", "5", "6"] },
  { q: "¿Qué país ha ganado más veces la Copa Davis?", a: "Estados Unidos", opts: ["España", "Australia", "Estados Unidos", "Francia"] },
  { q: "¿Cuántos metros es el salto de longitud del récord mundial?", a: "8.95 m", opts: ["8.50 m", "8.75 m", "8.95 m", "9.10 m"] },
  { q: "¿Cuántos jugadores tiene un equipo de balonmano?", a: "7", opts: ["6", "7", "8", "9"] },
  { q: "¿Qué deporte es conocido como 'el deporte rey' en España?", a: "Fútbol", opts: ["Baloncesto", "Fútbol", "Tenis", "Ciclismo"] },
  { q: "¿Cuántos sets tiene un partido de tenis al mejor de 5?", a: "5 sets máximo", opts: ["3 sets máximo", "4 sets máximo", "5 sets máximo", "6 sets máximo"] },
  { q: "¿Qué significa ATP en tenis?", a: "Asociación de Tenistas Profesionales", opts: ["Circuito de Tenis Americano", "Asociación de Tenistas Profesionales", "Torneos de Alta Puntuación", "Asociación de Tenis Profesional"] },
  { q: "¿En qué deporte se puede hacer un 'smash'?", a: "En tenis, bádminton y voleibol", opts: ["Solo en tenis", "En tenis, bádminton y voleibol", "Solo en bádminton", "Solo en voleibol"] },
  { q: "¿Cuántos minutos tiene un cuarto en la NBA?", a: "12", opts: ["10", "12", "15", "20"] },
  { q: "¿Qué país ganó el mundial de fútbol de 2018?", a: "Francia", opts: ["Croacia", "Francia", "Bélgica", "Brasil"] },
  { q: "¿Cuántos puntos vale un touchdown en fútbol americano?", a: "6", opts: ["3", "6", "7", "2"] },
  { q: "¿Qué deporte tiene posiciones llamadas 'quarterback' y 'wide receiver'?", a: "Fútbol americano", opts: ["Rugby", "Fútbol americano", "Béisbol", "Lacrosse"] },
  { q: "¿En qué ciudad se celebran los Juegos Olímpicos de 2024?", a: "París", opts: ["Los Ángeles", "París", "Brisbane", "Tokyo"] },
  { q: "¿Quién tiene más Balones de Oro en la historia?", a: "Lionel Messi", opts: ["Cristiano Ronaldo", "Lionel Messi", "Ronaldo Nazário", "Zinedine Zidane"] },
  { q: "¿Cuántos kilómetros tiene una etapa de montaña típica del Tour de Francia?", a: "Alrededor de 200 km", opts: ["100 km", "150 km", "Alrededor de 200 km", "300 km"] },
  { q: "¿Qué jugador de baloncesto es conocido como 'Air Jordan'?", a: "Michael Jordan", opts: ["Kobe Bryant", "Michael Jordan", "LeBron James", "Magic Johnson"] },
  { q: "¿Cuántos metros tiene la distancia estándar de 'Sprint' en atletismo?", a: "100 metros", opts: ["50 metros", "100 metros", "200 metros", "400 metros"] },
  { q: "¿Qué deporte practica Rafa Nadal?", a: "Tenis", opts: ["Golf", "Pádel", "Tenis", "Squash"] },
  { q: "¿Cuántos jugadores hay en la pista en un partido de hockey hielo?", a: "6 por equipo", opts: ["5 por equipo", "6 por equipo", "7 por equipo", "4 por equipo"] },
  { q: "¿Qué es el 'slam dunk'?", a: "Mate en baloncesto", opts: ["Gol de cabeza en fútbol", "Mate en baloncesto", "Ace en tenis", "Home run en béisbol"] },
  { q: "¿Cuántos puntos vale un penalti anotado en fútbol?", a: "1 gol", opts: ["2 goles", "1 gol", "0,5 goles", "3 puntos"] },
  { q: "¿En qué país inventaron el hockey sobre hielo?", a: "Canadá", opts: ["EEUU", "Finlandia", "Suecia", "Canadá"] },
  { q: "¿Qué es el 'hat-trick' en fútbol?", a: "Tres goles del mismo jugador en un partido", opts: ["Tres penaltis en un partido", "Tres goles del mismo jugador en un partido", "Tres tarjetas amarillas", "Tres partidos consecutivos ganados"] },
  { q: "¿Cuántos metros nadan en los 400 metros libres?", a: "400 metros", opts: ["200 metros", "400 metros", "800 metros", "100 metros"] },
  { q: "¿Qué deporte tiene la Fórmula 1?", a: "Automovilismo", opts: ["Motociclismo", "Automovilismo", "Karting", "Rally"] },
  { q: "¿Quién ganó más veces el Tour de Francia?", a: "Lance Armstrong (7 veces, retirados)", opts: ["Eddy Merckx", "Lance Armstrong (7 veces, retirados)", "Bernard Hinault", "Miguel Induráin"] },
  { q: "¿Qué deporte tiene la Copa America?", a: "Fútbol", opts: ["Rugby", "Fútbol", "Baloncesto", "Tenis"] },
  { q: "¿Cuántas medallas olímpicas ganó Usain Bolt?", a: "8 medallas de oro", opts: ["6", "8 medallas de oro", "10", "5"] },
  { q: "¿En qué año ganó España el Mundial de fútbol?", a: "2010", opts: ["2006", "2010", "2014", "2018"] },
  { q: "¿Qué deporte tiene al jugador Cristiano Ronaldo?", a: "Fútbol", opts: ["Rugby", "Tenis", "Fútbol", "Baloncesto"] },
  { q: "¿Cuántos jugadores forman parte de un quinteto de baloncesto en pista?", a: "5", opts: ["4", "5", "6", "7"] },
  { q: "¿Qué es el 'offside' o fuera de juego?", a: "Posición adelantada ilegal en fútbol", opts: ["Falta técnica en baloncesto", "Posición adelantada ilegal en fútbol", "Infracción en rugby", "Movimiento ilegal en ajedrez"] },
  { q: "¿En qué año se creó la Champions League con ese formato?", a: "1992", opts: ["1985", "1990", "1992", "2000"] },
  { q: "¿Cuántos metros tiene la carrera de obstáculos de 110m vallas?", a: "110 metros", opts: ["100 metros", "110 metros", "120 metros", "200 metros"] },
  { q: "¿Qué es el 'Grand Slam' en tenis?", a: "Ganar los 4 torneos principales en el mismo año", opts: ["Ganar Wimbledon", "Ganar los 4 torneos principales en el mismo año", "Ganar 10 torneos en un año", "Clasificarse para todos los torneos del año"] },
  { q: "¿Cuántos puntos tiene un juego ganado a 15 en tenis?", a: "15-0, 30-0, 40-0 son puntuaciones, no el juego completo", opts: ["1 punto", "4 puntos", "15-0, 30-0, 40-0 son puntuaciones, no el juego completo", "3 puntos"] },
  { q: "¿Qué país organizó los JJ.OO. de verano de 2016?", a: "Brasil", opts: ["Argentina", "Brasil", "Colombia", "Chile"] },
  { q: "¿Cuántos jugadores tiene un equipo de fútbol sala?", a: "5", opts: ["4", "5", "6", "7"] },
  { q: "¿Qué deporte practica Serena Williams?", a: "Tenis", opts: ["Golf", "Tenis", "Squash", "Bádminton"] },
  { q: "¿En qué continente se juega la Copa Africana de Naciones?", a: "África", opts: ["América", "África", "Asia", "Europa"] },
  { q: "¿Qué es el 'doble falta' en tenis?", a: "Dos servicios fallidos consecutivos, punto perdido", opts: ["Error técnico del árbitro", "Dos servicios fallidos consecutivos, punto perdido", "Golpe fuera de banda", "Falta de pie"] },
  { q: "¿Cuántos jugadores forman un equipo de cricket?", a: "11", opts: ["9", "11", "13", "15"] },
  { q: "¿Qué premio recibe el mejor jugador del Mundial de fútbol?", a: "Balón de Oro", opts: ["Bota de Oro", "Balón de Oro", "Guante de Oro", "Copa del Mundo"] },
  { q: "¿Cuántos metros tiene la pileta de natación en los Juegos Olímpicos?", a: "50 metros", opts: ["25 metros", "50 metros", "100 metros", "75 metros"] },
  { q: "¿Qué es el 'bogey' en golf?", a: "Un golpe sobre el par del hoyo", opts: ["Un hoyo en uno", "Un golpe sobre el par del hoyo", "Dos golpes bajo el par", "El mejor resultado posible"] },
  { q: "¿Cuántos metros separan las porteras en un campo de fútbol americano?", a: "91.44 metros (100 yardas)", opts: ["80 metros", "91.44 metros (100 yardas)", "100 metros", "110 metros"] },
  { q: "¿Qué es el 'penal' en fútbol?", a: "Tiro libre desde el punto de penalti", opts: ["Falta dentro del área", "Tiro libre desde el punto de penalti", "Expulsión del portero", "Tiro de esquina"] },
  { q: "¿Cuántos puntos se obtienen por ganar en la liga española de fútbol?", a: "3", opts: ["2", "3", "4", "5"] },
];