// 500 truths and 500 dares for Truth or Dare game

export const TRUTHS = [
  // Personal & embarrassing
  '¿Cuál es tu mayor miedo?',
  '¿Cuál es la mentira más grande que has dicho?',
  '¿Qué es lo más vergonzoso que te ha pasado?',
  '¿Cuál es tu peor hábito?',
  '¿Qué cosa nunca le contarías a tus padres?',
  '¿Cuál es la app que más usas en secreto?',
  '¿Qué harías con 1 millón de euros?',
  '¿Cuál ha sido tu peor metedura de pata?',
  '¿Qué talento secreto tienes?',
  '¿Cuál es tu recuerdo más vergonzoso del colegio?',
  '¿Has roto alguna vez algo y lo has ocultado?',
  '¿Cuál es la cosa más rara que has comido?',
  '¿Qué es lo que más te arrepientes de haber hecho?',
  '¿Cuál es tu crush famoso más vergonzoso?',
  '¿Qué es lo más raro que has buscado en internet?',
  '¿Has llorado con una película de animación? ¿Cuál?',
  '¿Qué canción escuchas en secreto pero jamás admitirías?',
  '¿Cuál es la cosa más estúpida que has hecho por amor?',
  '¿Has fingido estar enfermo para no ir a algún sitio?',
  '¿Cuál es tu mayor defecto?',
  '¿A quién de tu familia le tienes menos paciencia?',
  '¿Cuánto dinero llevas ahora mismo en el bolsillo?',
  '¿Qué harías si tuvieras poderes invisibles durante un día?',
  '¿Cuál es la cosa más cara que has comprado sin necesitarlo?',
  '¿Has leído los mensajes de alguien sin permiso?',
  '¿Qué es lo primero que miras en una persona que te gusta?',
  '¿Cuál es tu mayor adicción sin que lo parezca?',
  '¿Te has hecho el dormido para no hablar con alguien?',
  '¿Cuál es tu nombre de usuario más vergonzoso de la infancia?',
  '¿Qué cosa cambiarías de ti mismo si pudieras?',
  '¿Cuál es el peor regalo que has recibido y qué dijiste?',
  '¿Has mentido en el currículum o en una entrevista?',
  '¿Qué piensas realmente del estilo del otro jugador?',
  '¿Cuál es la película o serie de la que finges haber visto?',
  '¿A qué persona famosa envidias y por qué?',
  '¿Cuál es el mayor error que has cometido con un amigo?',
  '¿Tienes algún alias o apodo que odias?',
  '¿Qué es lo que más te cuesta admitir que no sabes hacer?',
  '¿Cuál ha sido tu peor cita o quedada?',
  '¿Qué harías diferente si pudieras volver a tener 10 años?',
  '¿Cuál es la cosa más tonta de la que te has enorgullecido?',
  '¿Has copiado en algún examen? ¿Cómo?',
  '¿Cuál es la excusa más ridicula que has puesto para no salir?',
  '¿Qué comida detestas pero dices que te gusta para quedar bien?',
  '¿Cuál es tu obsesión más rara que nadie conoce?',
  '¿Cuál es la peor decisión que has tomado en tu vida?',
  '¿Has fingido saber hacer algo que no sabes?',
  '¿Cuál es la cosa más childish que sigues haciendo de adulto?',
  '¿Qué es lo más caro que has roto o perdido?',
  '¿Has enviado un mensaje al destinatario equivocado? ¿Qué decía?',
  // Romantic & spicy
  '¿Cuál es tu tipo de persona ideal físicamente?',
  '¿Has tenido crush con alguien que no debías?',
  '¿Cuál es la cosa más atrevida que has hecho con alguien?',
  '¿Has besado a alguien cuyo nombre no recordabas?',
  '¿Cuál es el piropo más vergonzoso que te han dicho o has dicho?',
  '¿Tienes algún ritual de cita romántica que nadie conoce?',
  '¿Cuál es tu mayor inseguridad cuando estás con alguien que te gusta?',
  '¿Has hecho ghosting alguna vez? ¿Por qué?',
  '¿Cuál es la cosa más romántica que has hecho y salió mal?',
  '¿Has tenido una relación que nadie de tu entorno aprobaba?',
  '¿Qué es lo primero que haces cuando te gusta alguien?',
  '¿Cuál es la canción que pondría de música de fondo si fuera el protagonista de una peli romántica?',
  '¿Has stalkeado a alguien en redes sociales? ¿A quién?',
  '¿Cuál es el mayor secreto romántico que guardas?',
  '¿Has tenido más de una conversación romántica a la vez?',
  '¿Qué farola o mensaje tuyo de amor te da más vergüenza ahora?',
  '¿Has llorado por alguien que apenas conocías?',
  '¿Cuál es la cosa más atrevida que has escrito en un mensaje?',
  '¿Tienes alguna fantasía romántica muy particular?',
  '¿Has hecho algo ilegal por amor? ¿Qué fue?',
  // Friends & social
  '¿Cuál es el secreto de un amigo que conoces y no deberías saber?',
  '¿Has hablado mal de alguien que considerabas tu amigo?',
  '¿Cuál es la persona de tu grupo de amigos que más te cae mal en secreto?',
  '¿Has faltado a una boda, cumpleaños o evento importante sin una razón real?',
  '¿Qué es lo más egoísta que has hecho con un amigo?',
  '¿Has contado un secreto de alguien aunque prometiste no hacerlo?',
  '¿Cuál es la pelea de amigos más ridícula que has tenido?',
  '¿Tienes amigos de las redes que nunca has visto en persona?',
  '¿Has preferido quedarte en casa antes que salir con amigos?',
  '¿Cuál es el favor más raro que te han pedido?',
  // Work & ambitions
  '¿Cuál es la profesión que te daría vergüenza admitir que querías de niño?',
  '¿Has llegado tarde al trabajo o colegio y mentido con la excusa?',
  '¿Cuál es tu mayor sueño que no le has contado a nadie?',
  '¿Qué harías si te tocara la lotería mañana?',
  '¿Has escaqueado algún trabajo o tarea importante?',
  '¿Cuál es la habilidad profesional que finges tener?',
  // Deep & reflective
  '¿Cuál es la cosa de la que más te arrepientes en tu vida hasta ahora?',
  '¿Qué persona de tu pasado te gustaría poder decirle algo que nunca dijiste?',
  '¿Cuál es tu mayor miedo existencial?',
  '¿Qué es lo que más te cuesta perdonar a los demás?',
  '¿Cuál es la cualidad que más admiras en ti mismo?',
  '¿Qué camino tomarías si pudieras empezar de cero?',
  '¿Cuál es la opinión que tienes y sabes que a la gente no le gusta?',
  '¿Qué te da más miedo del futuro?',
  '¿Cuál es la persona que más ha influido en quien eres hoy?',
  '¿Tienes alguna creencia o superstición que en público negarías?',
  // Funny & weird
  '¿Cuál es el nombre más ridículo que le pondrías a tu mascota?',
  '¿Has hablado solo en público sin darte cuenta?',
  '¿Cuál es el objeto más inútil que tienes en casa?',
  '¿Has cantado en la ducha tan alto que te han oído los vecinos?',
  '¿Cuál es tu fobia más irracional?',
  '¿Has intentado ligar y fallado estrepitosamente? Cuenta cómo.',
  '¿Cuál es tu foto de perfil antigua que más vergüenza te da?',
  '¿Has comido algo caído al suelo? ¿Cuántos segundos pasaron?',
  '¿Cuál es el emoji que más usas y por qué?',
  '¿Has enviado notas de voz en momentos inapropiados?',
  '¿Cuál es la teoría conspirativa que secretamente te parece creíble?',
  '¿Tienes alguna superpotencia ridícula que desearías tener?',
  '¿Cuál es el peor chiste que conoces pero te hace reír?',
  '¿Has llegado a una reunión con la ropa del revés sin darte cuenta?',
  '¿Cuál es la cosa más patética que has hecho para llamar la atención?',
  '¿Cuál es tu talento oculto más inútil?',
  '¿Has intentado hacer algo deportivo y quedado en ridículo?',
  '¿Cuál es el momento más torpe que recuerdas de ti mismo?',
  '¿Has fingido saber bailar y quedado fatal?',
  '¿Cuál es el peor corte de pelo que has tenido voluntariamente?',
  // More spicy/interesting
  '¿Tienes algún ritual extraño antes de dormir?',
  '¿Cuál es el sueño más raro que has tenido?',
  '¿Has despertado sin recordar cómo llegaste a casa?',
  '¿Cuál es la apuesta más estúpida que has hecho y perdido?',
  '¿Has tenido miedo de algo que parece ridículo para los demás?',
  '¿Cuál es la cosa más cara que has hecho en un impulso?',
  '¿Has mentido sobre tu edad alguna vez? ¿Para qué?',
  '¿Cuál es la cosa más infantil que te da vergüenza admitir que te encanta?',
  '¿Has hecho algo solo porque "todo el mundo lo hace"?',
  '¿Cuál es la situación más incómoda que has vivido?',
  '¿Has tenido un apodo en el colegio que preferirías olvidar?',
  '¿Cuál es la moda que seguiste y ahora te avergüenza?',
  '¿Qué es lo más raro que has coleccionado?',
  '¿Has mentido sobre cuánto alcohol bebes?',
  '¿Cuál es la cosa más escandalosa que has hecho en una fiesta?',
  '¿Has hecho algo que tus padres jamás perdonarían si lo supieran?',
  '¿Cuál es la persona que más te ha marcado negativamente?',
  '¿Has tenido un alter ego secreto en internet?',
  '¿Cuál es el mayor malentendido que has tenido con alguien?',
  '¿Has dicho "te quiero" sin sentirlo?',
  '¿Cuál es la cosa más cringe que has publicado en redes?',
  '¿Has enviado un mensaje en caliente que luego lamentaste?',
  '¿Cuál es el momento en que te sentiste más ridículo?',
  '¿Has intentado impresionar a alguien y salido por peteneras?',
  '¿Cuál es la excusa más elaborada que has inventado?',
  '¿Has fingido que no veías a alguien para no saludarle?',
  '¿Cuál es la tontería más cara que has comprado por internet?',
  '¿Has hecho scroll de madrugada y te has arrepentido?',
  '¿Cuál es el chisme más jugoso que sabes y no puedes contar?',
  '¿Has besado a alguien por una apuesta?',
  '¿Cuál es el plan más ridículo que has hecho para gustarle a alguien?',
  '¿Has fingido que algo te gustaba para encajar con un grupo?',
  '¿Cuál es la decisión más impulsiva que has tomado?',
  '¿Has ignorado una llamada de alguien importante?',
  '¿Cuál es el momento más dramático que has protagonizado?',
  '¿Has mentido sobre tus gustos musicales para impresionar a alguien?',
  '¿Cuál es el fallo más épico que has tenido jugando a algo?',
  '¿Has hecho trampa en un juego de mesa?',
  '¿Cuál es la película que has visto más veces sin admitirlo?',
  '¿Qué harías si descubrieras que tu mejor amigo te ha traicionado?',
  '¿Cuál es la actitud de otra persona que más te irrita sin razón?',
  '¿Has tenido envidia de alguien y no lo has admitido?',
  '¿Cuál es el momento en que más has dudado de ti mismo?',
  '¿Has hecho algo por pura presión social que después lamentaste?',
  '¿Cuál es el complejo físico que más te ha costado superar?',
  '¿Qué es lo que la gente no sabe de ti y si lo supieran se sorprenderían?',
  '¿Has guardado conversaciones o fotos de alguien sin que lo sepa?',
  '¿Cuál es el límite que nunca cruzarías en una relación?',
  '¿Has hecho algo para llamar la atención que salió peor de lo esperado?',
  '¿Cuál es la promesa más importante que has roto?',
  '¿Has dicho que estabas de acuerdo con algo que en realidad no te gustaba?',
  '¿Cuál es la cosa más arriesgada que has hecho físicamente?',
  '¿Has competido con alguien en secreto sin que lo supiera?',
  '¿Cuál es el momento en que más has llorado solo?',
  '¿Qué es lo que más te asusta de envejecer?',
  '¿Cuál es la conversación más difícil que has tenido?',
  '¿Has hecho algo que pusiste en riesgo tu trabajo o estudios?',
  '¿Cuál es la manía más extraña que tienes?',
  '¿Has tenido un presentimiento que resultó ser cierto?',
  '¿Cuál es la mentira que más tiempo has mantenido?',
  '¿Qué es lo que nadie sabe que te da miedo?',
  '¿Cuál es la cosa más loca que harías si supieras que nadie te va a juzgar?',
  '¿Has tenido celos sin motivo aparente?',
  '¿Cuál es la decisión que siempre defiendes pero en el fondo sabes que estuvo mal?',
  '¿Has fingido ser más valiente de lo que eres?',
  '¿Cuál es el mayor secreto que compartes con alguien y nadie más sabe?',
  '¿Has actuado de una manera que ahora te avergüenza por completo?',
  '¿Cuál es la canción que más te pone triste y por qué?',
  '¿Has hecho algo deliberadamente para que alguien se pusiera celoso?',
  '¿Cuál es el consejo que das siempre pero tú mismo no sigues?',
  '¿Qué es lo que más te cuesta decir en voz alta?',
  '¿Cuál es el mayor tabú personal que tienes?',
  '¿Has llorado por algo que parecía una tontería?',
  '¿Cuál es el plan más descabellado que has tenido para el futuro?',
  '¿Qué harías si pudieras leer la mente de alguien por un día?',
  '¿Cuál es la cosa más cringe que has hecho intentando ser cool?',
  '¿Has tenido algún momento de total pánico que no le has contado a nadie?',
  '¿Cuál es el hábito más raro que tienes cuando estás solo?',
  '¿Qué es lo más peligroso que has hecho y no te ha pasado nada?',
  '¿Cuál es la historia de la que presumes pero que en realidad estás exagerando?',
  '¿Has hecho algo que nadie sabe y que te cambia la vida si se descubre?',
  '¿Cuál es el recuerdo de infancia que más te da vergüenza?',
  '¿Qué es lo que más envidia sientes de los demás?',
  '¿Has mentido sobre tu pasado con alguien nuevo?',
  '¿Cuál es la peor cosa que has pensado de alguien que quieres?',
  '¿Qué harías si supieras que hoy es el último día de tu vida?',
  '¿Cuál es la mayor contradicción en tu forma de vivir?',
  '¿Has actuado como si te importara algo que en realidad te era indiferente?',
  '¿Cuál es la persona con la que menos ganas tienes de coincidir?',
  '¿Tienes algún vicio que intentas esconder?',
  '¿Cuál es la obsesión que tienes con alguien famoso?',
  '¿Has comprado algo avergonzándote de hacerlo?',
  '¿Cuál es la cosa más patética que has hecho por llamar la atención en redes?',
  '¿Has dicho que alguien te gusta sin ser del todo sincero?',
  '¿Cuál es el objeto más sentimental que posees?',
  '¿Has hecho algo simplemente para poder contarlo como anécdota?',
  '¿Cuál es la duda existencial que más te ronda por la cabeza?',
  '¿Qué es lo que cambiarías de tu pasado si pudieras?',
  '¿Cuál es el insulto más creativo que has pensado pero no has dicho?',
  '¿Has fingido no saber algo que en realidad sabías?',
  '¿Cuál es la cosa más ridícula que has hecho por un like o reacción en redes?',
  '¿Has perdido a un amigo por algo que en retrospectiva fue una tontería?',
  '¿Cuál es la manía que tienes con la comida que a nadie confiesas?',
  '¿Has robado algo, por pequeño que sea?',
  '¿Cuál es la cosa más descarada que has pedido?',
  '¿Qué es lo que más te cuesta pedir perdón?',
  '¿Has tenido un pensamiento tan oscuro que te asustó a ti mismo?',
  '¿Cuál es el plan que has cancelado en el último momento sin una razón válida?',
  '¿Qué consejo darías a tu yo de hace 5 años?',
  '¿Cuál es la amistad que perdiste y que aún lamentas?',
  '¿Has actuado con doble cara con alguien?',
  '¿Cuál es tu peor rasgo de personalidad que reconoces?',
  '¿Qué es lo más raro que te ha puesto nervioso antes de una cita?',
  '¿Cuál es la situación social en la que más incómodo te has sentido?',
  '¿Has dicho "no tengo hambre" cuando en realidad morías de hambre?',
  '¿Cuál es el sabor, olor o sonido que te resulta desagradable pero finges tolerar?',
  '¿Qué regalo has regalado pero en realidad querías quedártelo?',
  '¿Cuál es la cosa más inmadura que has hecho recientemente?',
  '¿Qué harías si descubrieras que alguien te ha mentido durante años?',
  '¿Cuál es el momento en que más has querido desaparecer?',
  '¿Has dicho que ibas al baño para escapar de una conversación?',
  '¿Cuál es el momento en que más has reído sin poder parar?',
  '¿Qué es lo más torpe que has hecho delante de alguien que te gustaba?',
  '¿Cuál es la promesa que te has hecho a ti mismo y no has cumplido?',
  '¿Has fingido entender un chiste que no has entendido?',
  '¿Cuál es el mayor riesgo que has tomado en tu vida?',
  '¿Qué es lo que te haría abandonar todo y empezar de cero?',
  '¿Cuál es la opinión que nunca dirías en voz alta?',
  '¿Has tenido un sueño con alguien de tu entorno que te dio vergüenza?',
  '¿Cuál es el peor consejo que has dado y la otra persona siguió?',
  '¿Has actuado de forma diferente para encajar con un grupo?',
  '¿Cuál es la cosa más vergonzosa que has hecho en un transporte público?',
  '¿Qué es lo que más te pone de los nervios de ti mismo?',
  '¿Cuál es la mentira que más te costó mantener?',
  '¿Has comido a escondidas algo que habías prometido no comer?',
  '¿Cuál es el mayor error que has cometido con el dinero?',
  '¿Qué es lo que más te avergüenza de tu habitación?',
  '¿Has fingido que algo no te afectaba cuando en realidad sí?',
  '¿Cuál es el plan más elaborado que has hecho para evitar a alguien?',
  '¿Qué harías si nadie te juzgara durante 24 horas?',
  '¿Cuál es tu mayor fantasía de vida diferente a la que tienes?',
  '¿Has usado a alguien para conseguir algo?',
  '¿Cuál es la traición más pequeña que has hecho?',
  '¿Qué es lo que más te da miedo admitir sobre ti mismo?',
  '¿Cuál es la situación en que más has fingido estar bien?',
  '¿Has guardado rencor durante mucho tiempo?',
  '¿Cuál es la persona que más te ha sorprendido negativamente?',
  '¿Qué es lo más incongruente entre lo que predicas y lo que haces?',
  '¿Has sentido alivio cuando alguien canceló planes contigo?',
  '¿Cuál es el momento en que más has tenido que morder la lengua?',
  '¿Qué es lo que más envidia te da de la otra persona del juego?',
  '¿Cuál es la actitud tuya que más irrita a los demás sin que te lo digan?',
  '¿Has tenido una discusión importante por mensaje de texto?',
  '¿Cuál es el hábito de higiene más extraño que tienes?',
  '¿Qué es lo más irracional que has hecho movido por los celos?',
  '¿Cuál es la forma más ridícula en que has intentado impresionar a alguien?',
  '¿Has perdido algo valioso y dicho que nunca lo tuviste?',
  '¿Cuál es el trabajo que harías si el dinero no importara?',
  '¿Qué es lo que más te cuesta en una relación de amistad?',
  '¿Cuál es el mayor secreto que guardas sobre alguien de tu familia?',
  '¿Has hecho algo completamente fuera de tu zona de confort y lamentado?',
  '¿Cuál es la cosa más rara que te has preguntado en medio de la noche?',
  '¿Qué descubrir de alguien que quieres te destrozaría?',
  '¿Cuál es la situación en que más has actuado por orgullo puro?',
  '¿Has ignorado una señal de alarma importante en una relación?',
  '¿Cuál es el mayor malentendido que has causado tú sin querer?',
  '¿Qué es lo que más tardas en perdonar?',
  '¿Cuál es la cosa que más te avergüenza de tu historial de búsqueda?',
  '¿Has pensado en cortar el contacto con alguien y no te has atrevido?',
  '¿Cuál es tu reacción cuando alguien te dice algo que no quieres escuchar?',
  '¿Qué mentira diría alguien de ti que en realidad tiene algo de verdad?',
  '¿Cuál es la cosa más inapropiada que has dicho en el momento más inapropiado?',
  '¿Has fingido que algo te daba igual cuando en realidad te importaba mucho?',
  '¿Cuál es la razón más tonta por la que has dejado de hablar con alguien?',
  '¿Qué es lo que te hace sentir más solo aunque estés rodeado de gente?',
  '¿Cuál es la expectativa más irreal que has tenido de alguien?',
  '¿Has hecho algo para sabotear una situación que te daba miedo?',
  '¿Cuál es la cosa más antisocial que haces en casa?',
  '¿Qué es lo que más te cuesta decir en voz alta en una discusión?',
  '¿Cuál es la escapada más descabellada que has planeado y nunca has ejecutado?',
  '¿Has visto el teléfono de alguien mientras lo tenía desbloqueado?',
  '¿Cuál es el hábito más asqueroso que tienes cuando nadie te ve?',
  '¿Qué es lo que menos te gusta de ti mismo pero que nunca admitirías?',
  '¿Cuál es el mayor fracaso del que aún no te has recuperado?',
  '¿Has mentido sobre lo que sentías para no preocupar a alguien?',
  '¿Cuál es la cosa más romántica que has fantaseado pero nunca te has atrevido a hacer?',
  '¿Qué es lo que más te asusta de las relaciones serias?',
  '¿Cuál es el número máximo de veces que has visto el perfil de alguien en un día?',
  '¿Has llorado en el baño para que no te vieran?',
  '¿Cuál es el día de tu vida del que más te avergüenzas?',
  '¿Qué es lo que más te cuesta cuando conoces gente nueva?',
  '¿Cuál es la persona más famosa con la que desearías intercambiar tu vida?',
  '¿Has usado una excusa médica para librarte de algo?',
  '¿Cuál es la cosa más vergonzosa que has hecho cuando estabas nervioso?',
  '¿Qué harías si pudieras cambiar una decisión de tus padres?',
  '¿Cuál es el mayor truco mental que usas para convencerte de algo?',
  '¿Has hecho una foto o captura de pantalla de alguien sin que lo supiera?',
  '¿Cuál es la cosa más pesada que llevas emocionalmente ahora mismo?',
  '¿Qué es lo que más te da pereza hacer aunque sabes que deberías?',
  '¿Cuál es la última vez que lloraste y por qué?',
  '¿Has dejado pasar una oportunidad importante por miedo?',
  '¿Cuál es la cosa más inmadura que has hecho en una discusión?',
  '¿Qué es lo más absurdo que has hecho por aburrimiento?',
  '¿Cuál es la mayor trampa que has tendido a alguien?',
  '¿Has tenido un pensamiento muy oscuro sobre alguien que quieres?',
  '¿Cuál es el recuerdo que guardas y que nunca has compartido con nadie?',
  '¿Qué es lo que nadie sabe que te pone triste?',
  '¿Cuál es la mayor incongruencia entre tu imagen pública y la privada?',
  '¿Has hecho algo totalmente irracional y no te has arrepentido?',
  '¿Cuál es la cosa más desesperada que has hecho para conseguir algo?',
  '¿Qué es lo que más te cuesta aceptar de ti mismo?',
  '¿Cuál es la situación en que más has mentido convenciéndote de que era correcto?',
  '¿Has perseguido algo que en el fondo sabías que no era para ti?',
  '¿Cuál es el mayor sacrificio que has hecho por alguien y no fue valorado?',
  '¿Qué es lo que nadie sabe que te hace feliz?',
  '¿Cuál es el mayor malentendido que has tenido sobre ti mismo?',
  '¿Has fingido no estar celoso cuando lo estabas?',
  '¿Cuál es la cosa más ridícula por la que has discutido?',
  '¿Qué es lo que más te avergüenza de tu pasado romántico?',
  '¿Cuál es la cosa más egocéntrica que has hecho?',
  '¿Has reaccionado de forma exagerada ante algo menor?',
  '¿Cuál es la mayor hipocresía que reconoces en ti mismo?',
  '¿Qué es lo que más te cuesta decirle a alguien que quieres?',
  '¿Cuál es la cosa más oscura que has escrito o pensado?',
  '¿Has actuado de manera pasivo-agresiva con alguien?',
  '¿Cuál es el momento en que has sido más cobarde?',
  '¿Qué es lo que más te cuesta soltar cuando termina algo?',
  '¿Cuál es la cosa más descabellada que has creído durante mucho tiempo?',
  '¿Has hecho algo solo para demostrar que podías hacerlo?',
  '¿Cuál es la rutina más absurda que tienes?',
  '¿Qué es lo que más envidias de la vida de tus amigos?',
  '¿Cuál es el mayor malentendido que ha habido entre tú y tus padres?',
  '¿Has guardado algo de alguien que ya no está en tu vida?',
  '¿Cuál es la cosa más ingenua en la que has creído?',
  '¿Qué harías si pudieras vivir en otro país sin consecuencias?',
  '¿Cuál es tu mayor contradicción como persona?',
  '¿Has hecho algo completamente impulsivo y te ha salido bien?',
  '¿Cuál es la cosa más inesperada que te ha pasado en la vida?',
  '¿Qué es lo que más te molesta de ti cuando te pones nervioso?',
  '¿Cuál es la situación en que más difícil te ha resultado decir la verdad?',
  '¿Has hecho algo que considerabas imposible?',
  '¿Cuál es la cosa que más te cuesta dejar ir?',
  '¿Qué es lo que más te pesa en la conciencia?',
  '¿Cuál es el mayor error de comunicación que has tenido?',
  '¿Has hecho algo solo para evitar una conversación difícil?',
  '¿Cuál es la cosa más rara en la que has gastado dinero?',
  '¿Qué es lo que más te sorprende de quien eres hoy vs quien eras hace 5 años?',
  '¿Cuál es la cosa más increíble que te ha dicho alguien?',
  '¿Has hecho algo totalmente fuera de tu carácter?',
  '¿Cuál es el mayor cambio que has experimentado internamente?',
  '¿Qué es lo que más te enseñó tu mayor fracaso?',
  '¿Cuál es la cosa más valiente que has hecho?',
  '¿Has actuado de forma diferente dependiendo de con quién estabas?',
  '¿Cuál es el mayor aprendizaje de tu vida hasta ahora?',
  '¿Qué es lo que más necesitas escuchar hoy pero nadie te dice?',
  '¿Cuál es la cosa más importante que has perdido y no has recuperado?',
  '¿Has sonreído cuando en realidad estabas destrozado por dentro?',
  '¿Cuál es el mayor esfuerzo que has hecho por alguien?',
  '¿Qué es lo que te da más miedo que la gente sepa de ti?',
  '¿Cuál es la cosa más vulnerable que has compartido con alguien?',
  '¿Has dicho adiós a algo que te costó mucho?',
  '¿Cuál es la mayor verdad que has tenido que enfrentarte?',
  '¿Qué harías si pudieras enviar un mensaje a tu yo del futuro?',
  '¿Cuál es la cosa más real que sientes ahora mismo?',
  '¿Has pensado que seríais mejor pareja tú y el otro jugador?',
  '¿Cuál es la cosa más atrevida que has pensado pero no has dicho?',
  '¿Qué es lo primero que harías si supieras que te queda un mes de vida?',
  '¿Cuál es la pregunta que más te incomoda que te hagan?',
  '¿Has tenido un sueño muy intenso que no puedes quitarte de la cabeza?',
  '¿Cuál es la cosa más espontánea que has hecho?',
  '¿Qué es lo que más te gustaría que alguien te dijera?',
  '¿Cuál es la persona que más te conoce de verdad?',
  '¿Has hecho algo solo porque nadie más se atrevía?',
  '¿Cuál es la cosa más gratuita que has hecho para hacer el bien?',
  '¿Qué es lo que más admiras de alguien con quien sueles estar en desacuerdo?',
  '¿Cuál es el mayor regalo no material que has recibido?',
  '¿Has cambiado de opinión radicalmente sobre algo importante?',
  '¿Cuál es la cosa más genuina que has hecho sin esperar nada a cambio?',
];

export const DARES = [
  // Physical & active
  'Imita a un animal durante 30 segundos',
  'Haz 10 flexiones ahora mismo',
  'Di el alfabeto al revés tan rápido como puedas',
  'Baila sin música durante 1 minuto',
  'Habla como un robot durante 2 turnos',
  'Haz tu mejor imitación de un político famoso',
  'Escribe tu nombre con el codo en el aire',
  'Haz una reverencia y di "a su servicio" al otro jugador',
  'Imita al otro jugador durante 1 minuto',
  'Haz el moonwalk por la habitación',
  'Habla en susurros durante los próximos 3 turnos',
  'Haz tu mejor cara de bebé llorando y aguanta 20 segundos',
  'Ponte en cuclillas y camina así por la habitación',
  'Haz 15 saltos de tijera cantando una canción al mismo tiempo',
  'Pon una cara de susto extremo durante 30 segundos sin reírte',
  'Haz una postura de yoga e invéntate un nombre para ella',
  'Intenta lamer tu codo durante 30 segundos',
  'Haz la mejor imitación de Cristiano Ronaldo celebrando un gol',
  'Habla de ti mismo en tercera persona durante los próximos 2 turnos',
  'Ponte de pie en un pie durante 1 minuto mientras hablas de tu película favorita',
  'Haz 10 sentadillas mientras dices el nombre de un famoso en cada una',
  'Haz la imitación de cómo crees que el otro jugador duerme',
  'Haz 20 abdominales ahora mismo',
  'Salta sobre un pie mientras cantas el himno nacional',
  'Haz la postura del árbol durante 45 segundos',
  'Intenta tocarte los pies sin doblar las rodillas durante 30 segundos',
  'Camina hacia atrás hasta la pared y vuelve sin mirar',
  'Haz 5 lagartijas con palmada en el medio',
  'Baila el macarena completo sin música',
  'Aguanta en posición de plancha durante 45 segundos',
  'Haz el robot durante un turno entero',
  'Intenta hacer equilibrio con un objeto en la cabeza durante 30 segundos',
  'Corre en el sitio durante 30 segundos mientras cuentas hacia atrás',
  'Haz el movimiento de twerking durante 15 segundos',
  'Baila como si acabaras de ganar un millón de euros',
  // Voice & sound
  'Cuenta un chiste. Si no hace gracia, haz 5 sentadillas',
  'Envía un mensaje de voz con una voz graciosa a alguien de tu contactos',
  'Recita un poema inventado de 4 versos sobre la persona que tienes delante',
  'Actúa como si estuvieras en una película de acción durante 1 minuto',
  'Canta el intro de 3 series de televisión distintas',
  'Actúa como si acabaras de ganar un Oscar y da tu discurso de agradecimiento',
  'Convence al otro jugador de que eres de otro planeta en 1 minuto',
  'Actúa como si estuvieras leyendo las noticias más impactantes del mundo en TV',
  'Inventa y canta el jingle de un producto ridículo durante 30 segundos',
  'Habla solo en preguntas durante los próximos 2 minutos',
  'Imita el sonido de 5 animales en 30 segundos',
  'Di "supercalifragilisticoespialidoso" 3 veces sin equivocarte',
  'Canta una canción de amor dedicada al objeto más cercano a ti',
  'Habla con acento extranjero durante 2 turnos',
  'Imita a un YouTuber famoso en plena grabación durante 30 segundos',
  'Di un trabalenguas 3 veces seguidas cada vez más rápido',
  'Canta el "cumpleaños feliz" como si fuera una canción de metal',
  'Recita un rap de 8 barras sobre la persona que tienes delante',
  'Imita a un noticiero presentando tu vida como si fuera una noticia',
  'Habla sin usar la letra "a" durante 1 minuto entero',
  'Di el nombre de 20 países en 30 segundos',
  'Canta una canción cambiando todas las palabras por "patata"',
  'Haz una entrevista imaginaria a una silla como si fuera un famoso',
  'Narra en voz alta lo que está haciendo el otro jugador como si fuera un documental de naturaleza',
  'Actúa como un chef presentando la bebida que tienes delante como si fuera un plato Michelin',
  // Social & daring
  'Llama a alguien de tu agenda y canta "Cumpleaños feliz"',
  'Llama a alguien por teléfono y di "¿Eres tú el que me debe dinero?"',
  'Envía un mensaje a alguien diciendo "Necesito contarte algo importante" y espera su reacción',
  'Publica una foto rara tuya ahora mismo en tu historia de Instagram o WhatsApp',
  'Manda un audio de 1 minuto a alguien contando un chiste malísimo',
  'Envía un GIF o sticker sin contexto a la última persona con la que hablaste',
  'Escribe un tweet o publicación filosófica totalmente inventada',
  'Llama a alguien que no hablas desde hace mucho y dile que le echas de menos',
  'Envía un mensaje a un grupo diciendo "¿Alguien más huele a queso?"',
  'Pon una historia de WhatsApp con la cara más rara que pongas ahora',
  'Escribe un comentario positivo a la última foto de alguien que no conoces mucho',
  'Manda un mensaje en cadena ridículo a 3 personas',
  'Cambia tu foto de perfil de WhatsApp por la que te haga el otro jugador',
  // Creative & funny
  'Dibuja al otro jugador con los ojos cerrados en 30 segundos',
  'Inventa una coreografía de 8 pasos y enséñasela al otro',
  'Haz una entrevista de trabajo imaginaria al otro jugador para el puesto de "superhéroe"',
  'Actúa como si estuvieras viendo el partido de tu vida durante 30 segundos',
  'Haz el mayor grito silencioso que puedas durante 10 segundos',
  'Haz tu mejor imitación de un turista perdido preguntando direcciones',
  'Di una piropo ridículo al otro jugador con toda la seriedad posible',
  'Actúa como si fueras un chef de estrella Michelin describiendo una galleta',
  'Pon una cara de susto extremo durante 30 segundos sin reírte',
  'Explica cómo hervir agua como si fuera la receta más complicada del mundo',
  'Describe el techo de la habitación como si fuera una obra de arte maravillosa',
  'Actúa como si acabas de descubrir que eres invisible durante 30 segundos',
  'Haz de traductor simultáneo de lo que diga el otro jugador en un idioma inventado',
  'Presenta al otro jugador como si fuera el protagonista de una película de acción',
  'Actúa como un presentador de teletienda vendiendo tu calcetín',
  'Imita a 3 profesores o personas de autoridad que hayas tenido',
  'Actúa como si tuvieras retraso de 10 segundos en todo lo que haces',
  'Convierte en canción cualquier frase que te diga el otro jugador',
  'Haz como si estuvieras buceando en las profundidades del océano durante 30 segundos',
  'Actúa como si tu mano izquierda fuera una persona diferente a ti durante 1 minuto',
  'Haz la presentación de un producto inexistente y totalmente inútil',
  'Escribe una carta de amor a tu plato de comida favorito y léela en voz alta',
  'Actúa como si acabaras de llegar de una misión espacial de 6 meses',
  'Convierte el nombre del otro jugador en un acrónimo de alabanzas',
  'Haz como si estuvieras en una subasta y "vende" un objeto de la habitación',
  // Embarrassing & bold
  'Muestra la última foto que has hecho con el móvil',
  'Muestra el último meme que has enviado',
  'Lee el último mensaje que enviaste en voz alta',
  'Muestra la última búsqueda de Google que hiciste',
  'Di cuál es tu canción favorita ahora mismo (sin mentir)',
  'Muestra tu lista de reproducción más escuchada',
  'Di el nombre completo y apellidos de tu crush actual',
  'Muestra la última conversación de WhatsApp abierta (al menos 3 mensajes)',
  'Abre tu carpeta de fotos de hace 3 años y muestra la primera que aparezca',
  'Lee el último comentario que has puesto en redes sociales',
  'Di en voz alta la contraseña de alguna cuenta sin importancia',
  'Muestra tu historial de búsqueda de YouTube',
  'Lee el último tweet o post que hayas dado like',
  'Di el nombre de la persona que más has buscado en Instagram',
  'Muestra el fondo de pantalla de tu teléfono y explica por qué lo tienes',
  // More challenges
  'Come algo que mezcles tú mismo con ingredientes que haya en casa (solo si es seguro)',
  'Haz el desafío de mantener hielo en la mano durante 30 segundos',
  'Come una cucharada de algo que no te guste nada',
  'Bebe algo que te mezcle el otro jugador (dentro de lo razonable)',
  'Haz el reto de la cuchara: aguanta una cuchara colgando de la nariz el máximo tiempo',
  'Intenta hacer un nudo con una pajita solo con la boca',
  'Haz el reto de comer una galleta desde la frente hasta la boca sin manos',
  'Aguanta 30 segundos sin parpadear',
  'Intenta silbar una canción que el otro adivine',
  'Haz el reto: di la palabra "hola" en 10 idiomas distintos',
  'Muestra un talento real que nadie conoce ahora mismo',
  'Haz una reverencia de samurái y di "el honor es mío" con acento japonés',
  'Inventa 5 apodos creativos para el otro jugador en 30 segundos',
  'Di un halago sincero y específico a alguien que no sea el otro jugador, pero enviándoselo por mensaje',
  'Haz el "worm" (gusano) si puedes, o intenta durante 30 segundos',
  'Actúa como si acabaras de ganar la lotería durante 30 segundos',
  'Haz de comentarista deportivo de lo que está haciendo el otro jugador ahora mismo',
  'Intenta hacer el sonido más parecido posible al de una lavadora',
  'Actúa como si tuvieras 90 años explicando cómo funciona un smartphone',
  'Haz el moonwalk hacia atrás 5 pasos completos',
  'Describe con lujo de detalles cómo es tu método para doblar la ropa (o admite que no la doblas)',
  'Actúa como un perrito feliz durante 30 segundos',
  'Haz el reto de hablar solo en emojis describiendo tu día (el otro debe adivinar)',
  'Escribe con el dedo en la espalda del otro jugador una palabra y él debe adivinarla',
  'Haz el desafío de recordar el número de teléfono de alguien de memoria',
  'Canta tu nombre con la melodía de una ópera durante 30 segundos',
  'Di 10 cosas que te gustan del otro jugador sin parar y sin repetir',
  'Actúa como si fueras un personaje de videojuego durante 1 minuto',
  'Haz el "chicken dance" completo',
  'Intenta hacer 3 malabares con objetos pequeños (bolígrafos, monedas, etc.)',
  'Escribe una crítica de 1 estrella de ti mismo como si fueras un producto de Amazon',
  'Actúa como si estuvieras protagonizando un anuncio de colonia o perfume durante 30 segundos',
  'Deja que el otro jugador cambie tu estado de WhatsApp durante 10 minutos',
  'Permite que el otro jugador te peine el pelo de la forma más ridícula posible',
  'Haz un selfie con la cara más rara que puedas y ponla de foto de perfil 5 minutos',
  'Di un secreto que nunca hayas contado (pequeño, no hace falta que sea enorme)',
  'Llama a alguien importante para ti y dile algo bonito que nunca le has dicho',
  'Haz el acento de otro país durante 1 turno entero y mantén la conversación',
  'Actúa como si fueras un crítico de arte analizando el techo de la habitación',
  'Intenta adivinar el número de objetos en la habitación a simple vista (sin contar)',
  'Haz el reto de no tocar tu cara durante los próximos 5 minutos',
  'Actúa como si el suelo fuera lava durante 30 segundos',
  'Di el abecedario completo en menos de 3 segundos',
  'Haz el "floss dance" durante 30 segundos',
  'Actúa como un robot que se está quedando sin batería durante 30 segundos',
  'Haz el tutorial de "cómo ser el otro jugador" en 1 minuto',
  'Inventa una teoría conspiranóica sobre el objeto más mundano de la habitación',
  'Haz el pato andando durante 20 pasos',
  'Actúa como un chef irritable de Gordon Ramsay criticando un plato que el otro jugador inventa',
  'Di 5 palabras inventadas con su "definición oficial"',
  'Haz el desafío de no sonreír mientras el otro hace muecas durante 30 segundos',
  'Actúa como si te acabaran de dar una noticia impactante durante 30 segundos',
  'Haz el reto de comer palomitas (o cualquier snack) lanzándolas al aire y atrápandolas con la boca',
  'Escribe un horóscopo inventado para el otro jugador y léelo con total seriedad',
  'Actúa como si estuvieras completamente perdido en el bosque durante 30 segundos',
  'Di tu número favorito y justifícalo con la mayor solemnidad posible',
  'Haz el desafío de decir trabalenguas de otros idiomas (puedes inventarlos)',
  'Actúa como si estuvieras en una entrevista de trabajo para el puesto de "rey del mundo"',
  'Escribe un SMS de ruptura a una planta de la habitación',
  'Di 3 cosas que harías si fueras el otro jugador por un día',
  'Haz el reto de describir tu vida en menos de 10 palabras',
  'Actúa como si fueras un reportero cubriendo la escena de un crimen en la cocina',
  'Haz la narración épica de cómo te lavas los dientes',
  'Di el número máximo de idiomas en que sabes decir "te quiero"',
  'Actúa como si nunca hubieras visto un teléfono y te lo explican por primera vez',
  'Haz el monólogo de un villano que quiere conquistar la nevera',
  'Di 5 cosas que empiecen con la primera letra de tu nombre en 10 segundos',
  'Actúa como si fueras el narrador de un documental sobre el sofá de tu casa',
  'Haz el reto del espejo: repite todo lo que hace el otro jugador durante 30 segundos',
  'Escribe una nota de suicidio (dramática) sobre haber acabado el champú',
  'Actúa como si fueras un bebé intentando aprender a caminar durante 20 segundos',
  'Di el nombre de 10 marcas de coches en 15 segundos',
  'Haz el reto de los emojis: comunícate solo con gestos faciales durante 1 minuto',
  'Actúa como si te estuvieras despertando de una siesta de 20 años como Rip Van Winkle',
  'Haz una pose de superhéroe y mantente así durante 20 segundos',
  'Inventa un nuevo deporte olímpico y explica sus reglas en 30 segundos',
  'Actúa como si el otro jugador fuera tu mascota durante 30 segundos',
  'Haz el reto de decir "te quiero" de 5 formas diferentes en 30 segundos',
  'Actúa como si estuvieras buceando en el mar durante 30 segundos',
  'Di el discurso de un presidente que acaba de ganar las elecciones gracias a los gatos',
  'Haz el reto de recordar los nombres de todos tus profes del colegio que puedas en 1 minuto',
  'Actúa como si estuvieras en Matrix esquivando balas durante 20 segundos',
  'Haz el "scat" de jazz durante 30 segundos',
  'Actúa como si fuera la primera vez que ves la lluvia durante 20 segundos',
  'Di la capital de 10 países en 20 segundos',
  'Haz el reto de mantener la cara seria mientras el otro te hace cosquillas verbales (diciendo cosas graciosas) durante 30 segundos',
  'Actúa como un maestro explicando la teoría de la relatividad a niños de 5 años',
  'Haz el reto del "aburrimiento": actúa como la persona más aburrida del mundo durante 30 segundos y el otro debe entretenerte',
  'Describe tu comida favorita de una forma tan apetitosa que al otro le entre hambre',
  'Actúa como si fueras un fantasma que intenta comunicarse durante 30 segundos',
  'Haz el reto de adivinar qué objeto está pensando el otro jugador haciendo 10 preguntas de sí/no',
  'Actúa como si te acabara de picar una abeja en la nariz durante 20 segundos',
  'Di 10 palabras que rimen con "amor" en 15 segundos',
  'Haz el reto de intentar doblar la lengua en tubo (o demostrar que puedes/no puedes)',
  'Actúa como si fueras un conductor de autobús muy dramático durante 30 segundos',
  'Haz el reto de ponerte una prenda de ropa del revés sin quitártela',
  'Actúa como si acabaras de recibir una llamada que cambia tu vida durante 20 segundos',
  'Di 5 palabras raras que existen en español que no usa nadie',
  'Haz el reto de hacer el sonido de cada instrumento de una orquesta en 1 minuto',
  'Actúa como si fueras un dinosaurio que acaba de descubrir un smartphone',
  'Haz el reto de contar hasta 20 en otro idioma que no sea el tuyo',
  'Di la lista de la compra que llevarías si supieras que el mundo se acaba mañana',
  'Actúa como si estuvieras atrapado en arena movediza durante 20 segundos',
  'Haz el "running man" (el baile) durante 30 segundos',
  'Actúa como si fueras un mago y el objeto más cercano desapareciera mágicamente',
  'Di tus 3 mejores cualidades como si estuvieras en una entrevista y no pudieras mentir',
  'Haz el reto de imitar la voz de 5 personajes de dibujos animados',
  'Actúa como si te acabaran de robar la billetera y buscaras al ladrón frenéticamente',
  'Haz el tutorial de cómo ligar, pero al estilo del siglo XIX',
  'Di la receta de un plato inventado con los ingredientes más extraños posibles',
  'Actúa como si fueras un científico loco presentando su invento al mundo',
  'Haz el reto de decir el abecedario solo con vocales (a-e-i-o-u) musicalmente',
  'Actúa como si estuvieras intentando atrapar una mariposa invisible durante 30 segundos',
  'Di algo que genuinamente admires del otro jugador (tiene que ser verdad)',
  'Haz el reto de no decir "sí" o "no" durante los próximos 2 minutos',
  'Actúa como si fueras un pingüino caminando hacia el mar durante 20 segundos',
  'Haz el reto de adivinar a qué famoso está pensando el otro en 10 preguntas',
  'Actúa como si estuvieras jugando al ajedrez con suma concentración... solo (sin tablero)',
  'Di 10 nombres de frutas en 10 segundos (sin repetir)',
  'Haz el reto de silbar una canción y que el otro adivine cuál es',
  'Actúa como si fueras el personaje de una telenovela recibiendo una mala noticia',
  'Haz el reto del "espejo emocional": el otro dice una emoción y la actúas durante 10 segundos (5 emociones)',
  'Di el trabalenguas "Tres tristes tigres" 5 veces cada vez más rápido',
  'Actúa como si fuera la primera vez que comes un helado durante 30 segundos',
  'Haz el reto de adivinar una película con mímica en 1 minuto',
  'Actúa como si acabaras de llegar a un planeta desconocido y todo te sorprende',
  'Haz el baile del "Gangnam Style" durante 30 segundos',
  'Di qué animal serías y por qué en menos de 20 segundos',
  'Actúa como si estuvieras transmitiendo en vivo para un millón de personas los próximos 30 segundos',
  'Haz el reto de construir la torre más alta posible con objetos de la mesa en 1 minuto',
  'Actúa como si fueras un político dando un discurso sobre la importancia de las patatas fritas',
  'Di 5 "facts" completamente inventados con total convicción',
  'Haz el reto del karaoke: canta la primera canción que el otro jugador diga',
  'Actúa como si tu silla fuera un caballo y lo montes para dar la vuelta a la habitación',
  'Haz el reto de describir a alguien de tu entorno con solo 3 emojis y el otro adivina quién es',
  'Di un monólogo de 30 segundos sobre por qué la pizza es superior a todos los alimentos',
  'Actúa como si fueras un presentador de concurso televisivo muy emocionado durante 30 segundos',
  'Haz el reto de demostrar que sabes hacer algo que en realidad no sé si sabes (el otro elige)',
];